### ISSUE TITLE
Get Username and Password from ReportViewer

### ISSUE THREAD

**Issue by TheEagle82** [Microsoft/Reporting-Services#101]
Your code is great. It helped me implement our custom security for the Reporting Services. Howerver, I am facing a problem when using ReportViewer user control in asp.net. I am passing the username and password:

testrpt.ServerReport.ReportServerCredentials = new ReportServerCredentials(username, password);

But in the AuthenticationExtension, I couldn't find this username. Can you please help?

**Comment by gboreki** [comment]
You need to implement your own version of IReportServerCredential which implements the method GetFormsCredentials and returns the values you want used to the LogonUser api.

https://msdn.microsoft.com/en-us/library/microsoft.reporting.winforms.reportservercredentials.getformscredentials.aspx
