### ISSUE TITLE
Ability to create new PBI server report user, using API.

### ISSUE THREAD

**Issue by ishapkin** [Microsoft/Reporting-Services#104]
Hi! 
We have a web-application with users database (email as login, password).
Can we automatically to create user with existing data using your API?

**Comment by jtarquino** [comment]
PBI RS doesn't manage users, it uses Windows Users for authentication and you will have to use the APIS of your active directory or windows machine to create and manage the users, if you choose to implement your own custom security extension then you will have to create the users in the repository you used when you implemented the security extension

**Comment by ishapkin** [comment]
@jtarquino thank you!
