### ISSUE TITLE
No persmission users

### ISSUE THREAD

**Issue by KratosKen023** [Microsoft/Reporting-Services#112]
How can I add permissions to the user that is already registered?
I need access the folder with reports and assign roles to registered users.

![screenshot 39](https://user-images.githubusercontent.com/43458045/45855001-9e0e4900-bd80-11e8-822a-bb3b9ecc9fb3.png)

**Comment by jtarquino** [comment]
You need to login with the administrator you configured in https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample#step-3-deployment-and-configuration 
```
<AdminConfiguration>
    <UserName>username</UserName>
</AdminConfiguration>
```
That user can provide permissions to the users you registered
