### ISSUE TITLE
SSRS 2017 custom authentication and ReportServer database in SQL Server Cluster

### ISSUE THREAD

**Issue by SLazaroc** [Microsoft/Reporting-Services#113]
After setting up custom authentication in SSRS 2017 using a single server for SQL Server 2017 and SSRS 2017, it working fine in this environment, however when we use a SQL Server Clusters for the ReportServer database can't log in into web portal and web service. there is also no error message in the Logs files, I wondering if there is extra configuration for this kind environment.

**Comment by manceelee** [comment]
Make sure you have same machine key on both rereportserver.config.   Also, please make sure the status on 'scale-out deployment' is joined.
