### ISSUE TITLE
Cannot access Web Portal

### ISSUE THREAD

**Issue by blazej-bien** [Microsoft/Reporting-Services#117]
I have implemented a custom authentication (based on Forms authentication) using Microsoft sample (https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample).

It is sample for SSRS/SQL Server 2017. In my case the reporting Services are installed on a web test server with a domain address accessible from intranet network. The database engine is installed on a second server. On the web server we also have IIS installed.

When accessing the Web portal (https://somedomain/reports) I am always redirected to the logon.aspx page even though I am already authenticated (User.Identity.IsAuthenticated returns true and User.Identity.Name returns correct user name on logon_aspx.page_load). The Forms authentication cookie is set. When I am authenticated I return from the Page_Load because otherwise I would end up with infinite redirection loop.

But I noticed that I can access the reports using the Report Server Service (i.e. https://somedomain/ReportServer):

 
![image](https://user-images.githubusercontent.com/35566462/47232912-602d3080-d3d1-11e8-8aae-89322f4806a9.png)

I can click a report and it will be displayed.
Furthermore I can connect to the Reporting Services using SSMS and Forms authentication:
 
![image](https://user-images.githubusercontent.com/35566462/47232987-9965a080-d3d1-11e8-809d-f138500e3d43.png)

And I can access the Reporting Services properties. So I have full access.

I am connecting using a user which have all permissions, i.e Authorization.IsAdmin is always true (see Authorization class in the sample). This class implements IAuthorizationExtension.

But I noticed that when accessing the web portal no Authorization.CheckAccess method is invoked at all!  So this migt be a clue. Only methods from AuthenticationExtension class are invoked. Here is my custom logs from this class:

Invoked SetConfiguration.	
Invoked GetUserInfo.	
GetUserInfo. Setting user identity. Authenticated: 'True', type: 'Forms', user name: 
Invoked SetConfiguration.	
Invoked GetUserInfo 2.	
GetUserInfo. Setting user identity. Authenticated: 'True', type: 'Forms', user name: 
Invoked SetConfiguration.	
Invoked GetUserInfo.	
GetUserInfo. Setting user identity. Authenticated: 'True', type: 'Forms', user name:

I have turned on extended logging for the Reporting Services (also including HTTP) but there is no error.

I also have local (developer) implementation of this sample on my local machine and it works fine. I can access the web portal (although I have tested it accessing it from local). 

So this is happening only on the test server. And this is happening for http and https (no matter which protocol is used).

I also compared logs from the local version to the test version but I did not found anything interesting.
So /reports requests is redirected to the logon.aspx even though forms auth cookie is set:

 
![image](https://user-images.githubusercontent.com/35566462/47233014-b26e5180-d3d1-11e8-8bfc-b7657cf125e3.png)

If I clear cookies I get few more requests until the cookie is set but the last request to /reports should be successful (as it is on the local env) but in my case it redirects back to the logon.aspx.

I have spent already two days troubleshooting this issue (trying various things) but with no luck. 
Could anybody help me with this?

**Comment by gboreki** [comment]
It sounds like the machine keys could be mismatched between the two processes? This would cause the portal to not be able to decrypt the cookie created by reportserver. Can you confirm that?

**Comment by blazej-bien** [comment]
I have resolved it!
The machine key was the same in both places. I mean the one configured for the Portal process (configured in RSPortal.exe.config) and the second for the service process (configured in rsreportserver.config). I noticed that the former one is copied/added automatically based on the latter one.

Generally I compared all config files using WinMerge (local env vs test env). And even used the same machine key values from the example (I was not generating new ones yet). So I had exactly same configuration (no typos or missing configuration).
Then I installed the reporting services on another server and configured Forms authentication. And it worked! I mean this Web Portal access.
So on the test server (the problematic one) I uninstalled reporting services and installed it again and of course configured the Forms authentication once again (the same configuration - no changes relatively to the previous one). And now it works!

So it looks that the problem was with reporting services installation.
Only difference in the installation (Forms auth configuration is the same) is that on test server I am using Developer edition now. I do not know if it has any impact but it works.
I have not yet tested it on the production server with "normal" edition but I will let you know about the result soon.

**Comment by gboreki** [comment]
I have seen issues when copying the config files where they move with different permissions which prevents the service from writing them. This could be one reason. In pbrRs you only need to set the machine keys in the rsreportserver.config and the server shoud propagate to other processes (this is not true for ssrs 2016).
