### ISSUE TITLE
No credential prompt when deploying using Visual Studio.

### ISSUE THREAD

**Issue by blazej-bien** [Microsoft/Reporting-Services#118]
I have implemented Forms authentication and when deploying using VS 2017 I get following message:
_The permissions granted to user '' are insufficient for performing this operation._

Note that user is empty ('') and there is no credential prompt as normal (when using builtin Windows authentication).

Any ideas?

**Comment by gboreki** [comment]
When you say when "deploying from Visual Studio", you mean when you are deploying from a reporting solution? Just confirming...

Is your server working with forms authentication otherwise? When you connect from the browser for example? Also, have you deployed the extension exactly as it is in this sample or is it something already modified? I'd suggest to start with the sample and ensure that one works first. 

If the above seem to be right, then a fiddler trace and a copy or the extension config files might be helpful.

**Comment by blazej-bien** [comment]
Actually I have some modification of the sample (I use SAML auth) but as you already suggested I keep it very simple to get it worked first. So I made only some minor modifications and Forms auth logic is the same as in the sample.

Yes, I have some SSRS project and I am trying to deploy it using VS 2017 (right click and "Deploy").
I noticed from my custom logs that that the identity which is returned/set from GetUserInfo method has empty Name property although IsAuthenticated is true and Type is "Forms":

_Setting user identity. Authenticated: 'True', type: 'Forms', user name: ''_

And here is code which I used:

```
public void GetUserInfo(out IIdentity userIdentity, out IntPtr userId)
        {
            _logger.Log(LogLevels.Info, "Invoked GetUserInfo.");
            // If the current user identity is not null,
            // set the userIdentity parameter to that of the current user 
            if (HttpContext.Current != null
                  && HttpContext.Current.User != null)
            {
                var identity = HttpContext.Current.User.Identity;
                _logger.Log(LogLevels.Info, $"GetUserInfo. Setting user identity. Authenticated: '{identity.IsAuthenticated}', type: '{identity.AuthenticationType}', user name: '{identity.Name}'.");
                userIdentity = identity;
                userId = IntPtr.Zero;
                return;
            }
//rest of the code...
}
```

So I changed above condition to:

```
 if (HttpContext.Current != null
                  && HttpContext.Current.User != null
                  && HttpContext.Current.User.Identity != null
                  && !string.IsNullOrEmpty(HttpContext.Current.User.Identity.Name))
```

And now the prompt is appearing!

Although when I enter a user name which has all permissions (or the one configured as Admin in the configuration) the prompt appears once again. So something is not working yet. When I investigate what extensions methods are invoked when accepting credentials and deploying reports I will be able to tell you more. Currently I have not yet investigated why it does not work.

As workaround I used following pattern:

```
        public void GetUserInfo(out IIdentity userIdentity, out IntPtr userId)
        {
            _logger.Log(LogLevels.Info, "Invoked GetUserInfo.");
            // If the current user identity is not null,
            // set the userIdentity parameter to that of the current user 
            if (HttpContext.Current != null
                  && HttpContext.Current.User != null
                  && HttpContext.Current.User.Identity != null
                  && !string.IsNullOrEmpty(HttpContext.Current.User.Identity.Name))
            {
                var identity = HttpContext.Current.User.Identity;
                _logger.Log(LogLevels.Info, $"GetUserInfo. Setting user identity. Authenticated: '{identity.IsAuthenticated}', type: '{identity.AuthenticationType}', user name: '{identity.Name}'.");
                userIdentity = identity;
                userId = IntPtr.Zero;
                return;
            }

            _logger.Log(LogLevels.Info, $"Is In Deployment Mode: '{Settings.Default.IsInDeploymentMode}'.");

            if (bool.Parse(Settings.Default.IsInDeploymentMode))
            {
                userIdentity = new GenericIdentity(Settings.Default.DeploymentUser, "Forms");
                userId = IntPtr.Zero;
                return;
            }

            // The current user identity is null. This happens when the user attempts an anonymous logon.
            // Although it is ok to return userIdentity as a null reference, it is best to throw an appropriate
            // exception for debugging purposes.
            // To configure for anonymous logon, return a Gener
            _logger.Log(LogLevels.Error, "Current context or user property is null.");
            throw new NullReferenceException("Anonymous logon is not configured. userIdentity should not be null!");
        }
```

So I switch to a "deployment" mode and then set deployment user (which has all rights needed) and this works. But drawback is that I need to switch to "deployment" mode.
