### ISSUE TITLE
Database Access Errors

### ISSUE THREAD

**Issue by yaheya** [Microsoft/Reporting-Services#119]
How do I Change the login credentials? I get the following error - 

An error occurred while attempting to verify the user.Cannot open database "UserAccounts" requested by the login. The login failed. Login failed for user 'ISANDC\ETS-4595B42-YQ$'.

**Comment by manceelee** [comment]
Seems like you have some problem with the database connection, check your computer account has access to db UserAccounts

**Comment by YvesR** [comment]
If you speak about the sample project it is a setting => `Properties.Settings.Default.Database_ConnectionString`, so check it in setting from you dll project.
