### ISSUE TITLE
Problem with permissions after signing in via Custom Auth extension

### ISSUE THREAD

**Issue by rmccabe24** [Microsoft/Reporting-Services#12]
Hi, I followed the instructions for developing the code and deploying.  I was able to login as expected, the only problem now is that I get a permissions error (rsAccessDenied) after I login

![image](https://cloud.githubusercontent.com/assets/6367545/21651754/c73d6c6e-d2a1-11e6-8e2c-5302c2a17561.png)

Any ideas how I set roles for my user stored in the "Users" table so I can get logged in and see my reports?

**Comment by sqlchicken** [comment]
Have you launched IE as admin (right click icon, run as administrator), and add yourself to admin group from the settings/gear icon in top right. After that, go to root of site (http://localhost/reportserver) and click on configure folder. Apply proper permission for roles there. When you're done try again in non-admin IE window.

**Comment by rmccabe24** [comment]
I opened the Gear icon in IE - how do I add myself to admin group from here? (I cant see a permissions option anywhere there or in "Internet Options").

When I navigate to http://localhost/reportServer, I now get the forms auth logon page from your sample.  So I cant click on "Configure Folder" unless I undo the custom extension configuration and put it back to what it was before?

**Comment by sqlchicken** [comment]
Sorry, was referring to gear icon in SSRS 2016 (site settings). In SSRS go to site settings, security and in there you can add user/AD group to role of system user or administrator.

Conversely you can use SSMS to connect to Report Services service. Expand the Security folder and from there you can assign roles.

**Comment by rmccabe24** [comment]
I got to the bottom of it - my problem was that I had missed my main user account name from this setting:

   <Security>
      <Extension Name="Forms" Type="Microsoft.Samples.ReportingServices.CustomSecurity.Authorization, Microsoft.Samples.ReportingServices.CustomSecurity" >
        <Configuration>
          <AdminConfiguration>
            <UserName>**_NAMEHERE!_**</UserName>
          </AdminConfiguration>
        </Configuration>
      </Extension>
    </Security>

Populating this with my account meant I could log in to the report server.  Thanks for your help! :0)
