### ISSUE TITLE
Where is the file

### ISSUE THREAD

**Issue by ReneNoelCruz** [Microsoft/Reporting-Services#120]
I can't find the file 
Microsoft.Samples.ReportingServices.CustomSecurity.dll

**Comment by manceelee** [comment]
you have to compile the project and you will find the file in bni folder.

**Comment by ReneNoelCruz** [comment]
Thank You. 
I thought I Build the Solution, but the step to fix the reference to Microsoft.ReportingServices.Interfaces was not done. Now I can compile and now I see the files.
