### ISSUE TITLE
Create more than one Admin Account on the Report Server

### ISSUE THREAD

**Issue by SiddyM** [Microsoft/Reporting-Services#122]
We are working on this RS code and are currently facing some issues with the code, related to Roles being assigned. When the user is given a new Role, from the Manage -> Security link, and click Apply, the role is assigned, but that same user  is still having only read access. So when on the dashboard the user clicks the ellipse button, it gives an error dialog, for other roles. Currently only the "Browser" role works for all users, but if I give say "Content Manager", it reflects in the UI but it breaks while trying to access that report from the dashboard, as it is still having only read only access. Also there is no exception thrown in the code as well, which will help us debug further.

The code allows only one administrator for Report Server. We wish to have more than one administrator role to login, meaning give write access as well to user roles rather than just read, as with scenario above.

My approach is currently to add one more admin username xml node in **app.config**, and then work my way round in "**Authorization.cs**" file, where we change the static variable "m_adminUserName" to a string array.
Or should I make use of SQL database table, create new "Users" table with a role column, and iterate through it?.

Is this solution feasible and recommended. Wanted some guidance or pointers on how to implement the same, and is there any other dependencies / impact due to the change with this new changes if implemented. Also what other things I have to keep in mind while making this new changes.

**Comment by YvesR** [comment]
Why you do not implement your own `isAdminbyDefault` function and implement this in `GetPermissions()` method ?

Here, for example is how I do it:

<details>
  <summary>Show code</summary>

    public StringCollection GetPermissions(string userName, IntPtr userToken, SecurityItemType itemType, byte[] secDesc)
    {
      #region CHANGES FOR GROUPISM (ENABLING GROUPS)

      var informer = new InformerAuthentication();
      string[] str = informer.GetUserGroup(userName);
      string actorName = informer.ActorName(userName);

      #endregion

      StringCollection permissions = new StringCollection();

      if (IsAdminByDefault(actorName))
      {
        foreach (CatalogOperation oper in m_CatOperNames.Keys)
        {
          if (!permissions.Contains((string) m_CatOperNames[oper]))
            permissions.Add((string) m_CatOperNames[oper]);
        }

        foreach (ModelItemOperation oper in m_ModelItemOperNames.Keys)
        {
          if (!permissions.Contains((string) m_ModelItemOperNames[oper]))
            permissions.Add((string) m_ModelItemOperNames[oper]);
        }

        foreach (ModelOperation oper in m_ModelOperNames.Keys)
        {
          if (!permissions.Contains((string) m_ModelOperNames[oper]))
            permissions.Add((string) m_ModelOperNames[oper]);
        }

        foreach (CatalogOperation oper in m_CatOperNames.Keys)
        {
          if (!permissions.Contains((string) m_CatOperNames[oper]))
            permissions.Add((string) m_CatOperNames[oper]);
        }

        foreach (ReportOperation oper in m_RptOperNames.Keys)
        {
          if (!permissions.Contains((string) m_RptOperNames[oper]))
            permissions.Add((string) m_RptOperNames[oper]);
        }

        foreach (FolderOperation oper in m_FldOperNames.Keys)
        {
          if (!permissions.Contains((string) m_FldOperNames[oper]))
            permissions.Add((string) m_FldOperNames[oper]);
        }

        foreach (ResourceOperation oper in m_ResOperNames.Keys)
        {
          if (!permissions.Contains((string) m_ResOperNames[oper]))
            permissions.Add((string) m_ResOperNames[oper]);
        }

        foreach (DatasourceOperation oper in m_DSOperNames.Keys)
        {
          if (!permissions.Contains((string) m_DSOperNames[oper]))
            permissions.Add((string) m_DSOperNames[oper]);
        }
      }
      else
      {
        AceCollection acl = DeserializeAcl(secDesc);
        foreach (AceStruct ace in acl)
        {
          /*     FOR GROUPS TO WHICH USER BELONGS
          ------------------------------------------------*/

          for (int i = 0; i < str.Length; i++)
          {
            if (0 == string.Compare(str[i], ace.PrincipalName, true,
                  CultureInfo.CurrentCulture))
            {
              foreach (ModelItemOperation aclOperation in ace.ModelItemOperations)
              {
                if (!permissions.Contains((string) m_ModelItemOperNames[aclOperation]))
                  permissions.Add((string) m_ModelItemOperNames[aclOperation]);
              }

              foreach (ModelOperation aclOperation in ace.ModelOperations)
              {
                if (!permissions.Contains((string) m_ModelOperNames[aclOperation]))
                  permissions.Add((string) m_ModelOperNames[aclOperation]);
              }

              foreach (CatalogOperation aclOperation in
                ace.CatalogOperations)
              {
                if (!permissions.Contains((string) m_CatOperNames[aclOperation]))
                  permissions.Add((string) m_CatOperNames[aclOperation]);
              }

              foreach (ReportOperation aclOperation in ace.ReportOperations)
              {
                if (!permissions.Contains((string) m_RptOperNames[aclOperation]))
                  permissions.Add((string) m_RptOperNames[aclOperation]);
              }

              foreach (FolderOperation aclOperation in ace.FolderOperations)
              {
                if (!permissions.Contains((string) m_FldOperNames[aclOperation]))
                  permissions.Add((string) m_FldOperNames[aclOperation]);
              }

              foreach (ResourceOperation aclOperation in ace.ResourceOperations)
              {
                if (!permissions.Contains((string) m_ResOperNames[aclOperation]))
                  permissions.Add((string) m_ResOperNames[aclOperation]);
              }

              foreach (DatasourceOperation aclOperation in ace.DatasourceOperations)
              {
                if (!permissions.Contains((string) m_DSOperNames[aclOperation]))
                  permissions.Add((string) m_DSOperNames[aclOperation]);
              }
            }
          }


          /*     FOR PARTICULAR USER 
          --------------------------------*/

          if (0 == string.Compare(actorName, ace.PrincipalName, true,
                CultureInfo.CurrentCulture))
          {
            foreach (ModelItemOperation aclOperation in ace.ModelItemOperations)
            {
              if (!permissions.Contains((string) m_ModelItemOperNames[aclOperation]))
                permissions.Add((string) m_ModelItemOperNames[aclOperation]);
            }

            foreach (ModelOperation aclOperation in ace.ModelOperations)
            {
              if (!permissions.Contains((string) m_ModelOperNames[aclOperation]))
                permissions.Add((string) m_ModelOperNames[aclOperation]);
            }

            foreach (CatalogOperation aclOperation in
              ace.CatalogOperations)
            {
              if (!permissions.Contains((string) m_CatOperNames[aclOperation]))
                permissions.Add((string) m_CatOperNames[aclOperation]);
            }

            foreach (ReportOperation aclOperation in ace.ReportOperations)
            {
              if (!permissions.Contains((string) m_RptOperNames[aclOperation]))
                permissions.Add((string) m_RptOperNames[aclOperation]);
            }

            foreach (FolderOperation aclOperation in ace.FolderOperations)
            {
              if (!permissions.Contains((string) m_FldOperNames[aclOperation]))
                permissions.Add((string) m_FldOperNames[aclOperation]);
            }

            foreach (ResourceOperation aclOperation in ace.ResourceOperations)
            {
              if (!permissions.Contains((string) m_ResOperNames[aclOperation]))
                permissions.Add((string) m_ResOperNames[aclOperation]);
            }

            foreach (DatasourceOperation aclOperation in ace.DatasourceOperations)
            {
              if (!permissions.Contains((string) m_DSOperNames[aclOperation]))
                permissions.Add((string) m_DSOperNames[aclOperation]);
            }
          }
        }
      }

      //AuthenticationUtilities.DebugLog(permissions.Cast<string>().Aggregate("", (current, entry) => current + (entry + " -- ")));
      return permissions;
    }
</details>

There you can just implement your own logic for `isAdminByDefault` where you can also store a collection or array of users.
