### ISSUE TITLE
Best way to share values between ReportServer and Portal

### ISSUE THREAD

**Issue by dark7622** [Microsoft/Reporting-Services#126]
So, here is the problem, I made a component that allows for Claims based authentication. It gets done via the ReportServer via the logon.aspx. Though when a user goes back to Reports (portal) none of the cookies, sessions, etc. seem to be populated, including the objects that hold the cookies (httpcontext, etc..)

Is there a better way? 

Right now I'm writing the encrypted serialized object to file in a "Users" folder and reading from that file if no cookie exists. Of course the data in the file has a timeout built in that I did when encrypting it (cert and expire). So if it's expired it will kick off the re-log in code. I just don't like having to write files, of course I could write to a DB, but I don't like that either. 

I understand that this is because ReportServer is running as asp.net, while portal is under OWIN control so there are different app domains and such. On the portal many of the asp.net classes we grown to love/hate are just not populated.

Be interesting to figure out another route.

**Comment by YvesR** [comment]
The only way imho (what I did) is to pass through the session cookie, store your values in a key-value table inside the db and use this in both platforms as you share the session cookie to identify your session to get the correct values.
