### ISSUE TITLE
I followed same steps but still I am getting HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by skvh30** [Microsoft/Reporting-Services#127]
`<MachineKey ValidationKey="VALIDATIONKEY" DecryptionKey="DECRIPTIONKEY" Validation="AES" Decryption="AES" /> `

Check the casing of the attributes, it should be Pascal Casing as the example above
and solved my problem.

_Originally posted by @ganeshlalasaheblondhe in https://github.com/Microsoft/Reporting-Services/issues/26#issuecomment-371468224_

**Comment by jtarquino** [comment]
I recommend to use the automatic script setup https://www.figma.com/file/B9dVLythbBVGn55VMJTrUd6D/Email-Subscriptions-for-Paginated-Report?node-id=42%3A1215 in a clean environment and compare with yours
