### ISSUE TITLE
Why does the docs page suggest adding the Microsoft.ReportViewer.WinForms and  Microsoft.ReportViewer.Design assemblies to a web project?

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/Reporting-Services#128]
Per the directions [here](https://docs.microsoft.com/en-us/sql/reporting-services/application-integration/integrating-reporting-services-using-reportviewer-controls-get-started?view=sql-server-2017#updating-an-existing-project-to-use-the-report-viewer-control) it says add these to a web project.  Including that Designer DLL causes several `assemblyBindingRedirects` to need to be included, yet the assembly isnt called by any code I can find in the project or by the other report viewer package assemblies.

I dont understand the need for a winforms dll at all.

**Comment by jtarquino** [comment]
Those are required to support the design time experience

**Comment by StingyJack** [comment]
@jtarquino then they need to be included in a separate tools package, declared as dev dependencies, or made as an extension to VS.  

Currently they are only serving as a potential source of runtime bugs.

**Comment by jtarquino** [comment]
We have the item in our backlog for future releases

**Comment by StingyJack** [comment]
Thanks, I'll accept that info as a closure reason.
