### ISSUE TITLE
Power BI desktop connect to report server got 401 status code, if form authentication for report server

### ISSUE THREAD

**Issue by Oldsooh** [Microsoft/Reporting-Services#129]
Hi,

 

Recently I have followed the custom security sample and successfully dit it for Power BI report server.  However, the following issues I have no idea how to solve it, please help to take a look:

 
**1. Power BI Desktop cannot connect to report server with form authentication**

  - The following logs showing UnAuthorized accessing had been rejected by report server:

  2019-01-05 21:17:57.2750|INFO|15|Sending response. Response code 401, Elapsed time 0:00:00.0013331| RequestID = s_7119ea54-901b-491f-b35d-8da679bf7e8f
2019-01-05 21:17:57.4322|INFO|15|Received request GET /api/v2.0/ServiceState| RequestID = s_cdbaf04b-bf0b-4c02-bd93-b1ba8acb36b1
2019-01-05 21:17:57.4322|INFO|15|Sending response. **Response code 401**, Elapsed time 0:00:00.0003215| RequestID = s_cdbaf04b-bf0b-4c02-bd93-b1ba8acb36b1
2019-01-05 21:17:57.6217|INFO|15|Received request GET /api/v2.0/ServiceState| RequestID = s_4f92d71c-1162-4cbd-8c9a-a43faa104c36
2019-01-05 21:17:57.6217|INFO|15|Sending response. **Response code 401,** Elapsed time 0:00:00.0003774| RequestID = s_4f92d71c-1162-4cbd-8c9a-a43faa104c36

 

**By the way, everything is OK with windows authentication, Power BI desktop can pushlish report to report server.**

 

 

**2. The user registerd from LogOn page can log on report, but then permission denied message poped up**

- After deployed custom security sample, I can only log on report (with corrected permission) using bulit-in Administator account, The bulit-in admin account is set here:

  
```
<Security>
	<Extension Name="Forms" Type="Microsoft.Samples.ReportingServices.CustomSecurity.Authorization, Microsoft.Samples.ReportingServices.CustomSecurity" >
	<Configuration>
		<AdminConfiguration>
			<UserName>username</UserName>
		</AdminConfiguration>
	</Configuration>
	</Extension>
</Security>
  ```

And I have a new account which registered from logon.aspx page. If I use this account and trying to log on report server, yes I logged on report server, but I have no permission to read report, an error dialog poped up and said permission denied.

 

 

Could you pls take a look for my 2 issues? Thanks in advance.

**Comment by jtarquino** [comment]
Power BI Desktop connecting to PBIRS is not supported with custom authentication

**Comment by Oldsooh** [comment]
> Power BI Desktop connecting to PBIRS is not supported with custom authentication

Thanks. How about the question 2?

> The user registerd from LogOn page can log on report, but then permission denied message poped up

**Comment by jtarquino** [comment]
You need to provide permissions to that account, in order to do that use the administrator account and add the new registered account to the folder you want to provide access
