### ISSUE TITLE
Works with mobile reports?

### ISSUE THREAD

**Issue by greblo** [Microsoft/Reporting-Services#13]
I configured an SSRS 2016 instance using the custom auth extension as described here; however, when I try to view datasets using the report portal, the portal throws the "misconfigured" exception as described here:
[https://connect.microsoft.com/SQLServer/feedback/details/3118953/cannot-load-dataset-data-in-report-portal-with-custom-security-extensions-for-report-services-2016](url)

Further, I cannot load mobile reports that have been configured to use the datasets, as described here:
[https://connect.microsoft.com/SQLServer/feedback/details/3118953/cannot-load-dataset-data-in-report-portal-with-custom-security-extensions-for-report-services-2016](url)

Have you had a chance to test the custom security using mobile reports?

Thanks!

**Comment by jtarquino** [comment]
We started to look at the issue, we will keep you updated

**Comment by greblo** [comment]
Jaime, thanks for your reply and for venturing to investigate this issue. I also have a few posts on technet about the experience, including:

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b978b36e-e9df-420d-9223-2012c383ff68/ssrs-2016-and-custom-authentication?forum=sqlreportingservices

However, there is nothing new in that thread, other than to say that an SSRS instance configured using the custom authentication extension will work fine for paginated reports, but seems to throw exceptions in the report portal when loading the data from a dataset in the report portal, or when loading a mobile report.

Thanks again!

**Comment by greblo** [comment]
I should have mentioned I was running SSRS 2016 on an instance of Windows 10. When I stood up a new SSRS 2016 instance on Windows Server 2012, the custom security extension worked with only a few issues (needed to change service account, for example). Sorry for the red herring.
