### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by Et3rnal** [microsoft/Reporting-Services#131]
The custom security is a great help, thanks

I'm trying to create a session using the restful API which works fine locally but asks for CORS as the server is a different domain.  But I can't find anything to help me enabling it? 
Is it possible? how?

I'm getting 400 bad requests
and
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://xx-ss-00.somewhere.cloudapp.azure.com/reports/api/v2.0/Session. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

**Comment by jtarquino** [comment]
Instructions to configure CORS  in SSRS 2017 https://docs.microsoft.com/en-us/sql/reporting-services/tools/server-properties-advanced-page-reporting-services?view=sql-server-2017

**Comment by Et3rnal** [comment]
I can't find any of these? here is what I'm using
SSRS V14.0.600
SSMS V14.0.17285.0

Can add them in code/configuration without the UI?

**Comment by Et3rnal** [comment]
Okay, I wasn't connecting with Service type set to Reporting Services.
Thanks for the help

**Comment by MarkMad** [comment]
I am using SSRS 2016 (v13.05101.9). I can't find it as an option in the Advanced tab. Is there another way to enable this option?

**Comment by Et3rnal** [comment]
Not sure about 2016, but 2017+ is different.
I thought rest APIs are part of 2017!

**Comment by jtarquino** [comment]
The supported REST API is only available in 2017 and later https://docs.microsoft.com/en-us/sql/reporting-services/developer/rest-api?view=sql-server-2017

**Comment by MarkMad** [comment]
The docs should remove mention of AccessControlAllowOrigin in https://docs.microsoft.com/en-us/sql/reporting-services/tools/server-properties-advanced-page-reporting-services?view=sql-server-2016 then.
