### ISSUE TITLE
How to redirect if no valid user is logged in?

### ISSUE THREAD

**Issue by YvesR** [Microsoft/Reporting-Services#132]
I have trouble ugrading my custom security extension to latest version.

In previous SSRS 2016/2017 custom security extension there was a `UILogin.aspx` and `UILogon.aspx.cs` where I had a `HttpContext.Current`. So if some called the `/reports` user interface I was able to check if user has a valid session and if not redirect to my login controller.
I still can do this with `/reportserver` as there I still have a `login.aspx`.

I did not find any info how to do this now with the new SSRS 2017. The user interface now is a own solution in `/Portal` subfolder of reporting services. Inside this folder we do have only some executes and dll files.

When I call `/reportserver` first, authenticate and return with a valid session I can call `/reports` with out any problems, all works fine including all authorization stuff.

So in my case I need info how to implement a **redirect to login controller** and after login return to 
portal.

This is my (simplified code) from login.aspx.cs:

      var rorSession = Request.Cookies["_ror_session"]?.Value;
      var domain = Request.Url.Host;
      if (rorSession != null) { ... }
      else
      {
        var rorUrl = "/ror/login?referer=";
        var returnUrl = "/ReportServer/logon.aspx?ReturnUrl=" + HttpUtility.UrlEncode(Request.QueryString["ReturnUrl"]);
        HttpContext.Current.Response.Redirect(rorUrl + HttpUtility.UrlEncode(returnUrl), false);
      }

I think I must do this in new `GetUserInfo` now, but `IRSRequestContext` gives only readonly information and no context for e.g. redirection...

    public void GetUserInfo(IRSRequestContext requestContext, out IIdentity userIdentity, out IntPtr userId)
    {
      userIdentity = null;
      if (requestContext.User != null)
      {
        userIdentity = requestContext.User;
      }
      else
      {
        // here we need somehow redirect now
        // ..
        var test = requestContext.Cookies["_ror_session"];
        userIdentity = new GenericIdentity("Anonymous");
      }

      // initialize a pointer to the current user id to zero
      userId = IntPtr.Zero;
    }

**So how do I achieve this with new SSRS user interface??**

**Comment by gboreki** [comment]
Hi YvesR,

Is your server configured with Forms authentication? If so, the redirection from the portal should happen automatically e.g. if the portal is not able to decrypt the cookie or if the cookie has expired you should be automatically redirected from /reports to /reportserver/logon.aspx. Once the user automatically authenticates, you should redirect back to the original portal url. This is the behavior that you should see with the sample. Are you not seeing this behavior?

Note that this behavior change was already present in SSRS2016, the last release to include the UILogin.aspx was SSRS2014.

Thanks
-G

**Comment by YvesR** [comment]
Hi,

I did and use the configuration like described in the custom security extension since 2008. Used in 2012 and 2014, and now I work on 2016/2017 to make it work here.

In this case reportserver.config:

		<AuthenticationTypes>
			
			<Custom/>
		</AuthenticationTypes>

Or do I miss something?

**Comment by gboreki** [comment]
No, seems fine. What is the behavior that you see when you navigate to /reports?

**Comment by YvesR** [comment]
I traced the code and see that in `GetPermissions` is called from portal. 
Could it be that `GetUserInfo` may not return any identity? I so return `GenericIdentity("Anonymous")` as this was from former solution.
