### ISSUE TITLE
Row level security 

### ISSUE THREAD

**Issue by manceelee** [Microsoft/Reporting-Services#135]
Hi all, 

     Is there there way to pass customized value to report itself, so query or measure is able to pick up the value and filter the data.  

Thanks.

**Comment by VaderConsulting** [comment]
I also would like to know if this is possible

**Comment by jtarquino** [comment]
Power BI Report Server latest version supports Row Level Security https://docs.microsoft.com/en-us/power-bi/report-server/row-level-security-report-server
