### ISSUE TITLE
rs.exe The Authentication Extension threw an unexpected exception

### ISSUE THREAD

**Issue by Et3rnal** [microsoft/Reporting-Services#136]
Can **rs.exe** connect to SSRS if custom security extension is in use?

I'm getting 
`Extension threw an unexpected exception or returned a value that is not valid: . (rsAuthorizationTokenInvalidOrExpired)`

If possible any idea guide? or idea what could be wrong? If not, what are the alternatives? 
I'm using 2017

**Comment by Et3rnal** [comment]
Can anyone confirm this, please ?

**Comment by YvesR** [comment]
I never used this, but I guess you have to implement a way to bypass your custom security extension (which probably authenticate against any third party user-database) and fall back to windows authentication used in common mode. So an idea would be something like checkup like you implemented and if authenticate fails you try implement a fallback to authenticate against network-login and use impersonating, e.g. https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.impersonate?redirectedfrom=MSDN&view=netframework-4.7.2#System_Security_Principal_WindowsIdentity_Impersonate_System_IntPtr_.

**Comment by Et3rnal** [comment]
Can you please elaborate more on your idea? As far as I know, custom authentication cannot be used with any other authentication type.

What are the alternatives to deploy SSRS reports?

**Comment by YvesR** [comment]
If you implement your own custom type you can implement default windows nltm auth as well there. So check for your auth, if it fails or is invalid then impersonate using windows auth inside your custom auth code.

Alternative is upload your reports using the UI by upload each rdl file (which I do).

**Comment by Et3rnal** [comment]
I got you. Any idea where to start from if I want to do my own deployment tool?
The problem in my case is that I need to make it easy for the client, I'm looking at the 3rd party deployment tools but I haven't tested any of them yet. Have you?

**Comment by YvesR** [comment]
I would infact do it here (example, not tested):

    public static bool VerifyUser(string userName)
    {
      bool flag = false;
      #region VERIFICATION THROUGH OWN SECURITY
       // do your code here
        var informer = new InformerAuthentication();
      flag = informer.ActorExists(userName);
      #endregion
      #region VERIFICATION THROUGH ACTIVE DIRECTORY
      if ( !flag ) {
        var ad = new ADauthentication();
        flag = ad.IsExists(userName);
      }
      #endregion
      return flag;
  
    }

And then you also have to implement this in `CheckAccess` for the required operations.
