### ISSUE TITLE
how to use script to grant the report access to all the users 

### ISSUE THREAD

**Issue by manceelee** [microsoft/Reporting-Services#138]
Hello, 

Is anyway to achieve this, basically I am trying to implement RLS and there are thousands of users, it's impossible to manually add them to the report, is there quick way to add those users to particular report by  sql script?  Thanks!

**Comment by YvesR** [comment]
This question is not related to this project, has nothing to do with security extension.
Nevertheless if you really want to do this:

1. `Catalog` stores your reports, folders
2. `Roles` stores the roles you want to set for users
3. `Users` holds your users that exists

Build a valid sql statement that fills `PolicyUserRole` table with valid data and your job is done.
