### ISSUE TITLE
Report Viewer 2016 for WebForms do not open PDFs in Chrome

### ISSUE THREAD

**Issue by adopilot** [Microsoft/Reporting-Services#14]
I am trying to implement SSRS Report Viewer 2016 control on my Webpage I did install package Microsoft.ReportingServices.ReportViewerControl.WebForms -Pre it is now on version 140.1.291.2731477-rc When I open page whit report-viewer it looks all right . When I try to print on chrome I get Print dialog for Page orientation and page size. After click on print, nothing happens. On chrome developer tools in console screen get message:

```
Resource interpreted as Document : 
Reserved.ReportViewerWebControl.axd?OpType=Resource&Version=14.0.1.291&Name=Microsoft.Reporting.Web…
but transferred with MIME type application/pdf: http://localhost:54071/Reserved.ReportViewerWebControl.axd?ReportSession
```
![image](https://cloud.githubusercontent.com/assets/4448913/22467660/c61a3ffe-e7c5-11e6-80b4-012387725089.png)

If I try to print in EDGE i get print screen dialog without problems.(PDF get opened)
If I try on Firefox I get PDF opened inside Dialog Window.

Can this issue be caused because report viewer control rendering report hosted on SSRS2012 services. (Control is 2016 version but it render remotely hosted SSRS2012 reports).

I did also try to instal Adobe PDF extension for CHROME but nothing again
Same message no PDF get oppened

**Comment by RhysSchmidtke** [comment]
Hi Adopilot, the print flow for Chrome is slightly different to the flow used for Firefox and IE and relies on the PDF being generated with 'print on open' property enabled which was only added in 2016. We've got a bug tracking the issue internally.

**Comment by ca0v** [comment]
Recent chrome changes seem to prevent PDF's from being viewed when generated by ReportViewer.  Anyone else seeing this?
