### ISSUE TITLE
Authorization options

### ISSUE THREAD

**Issue by Et3rnal** [microsoft/Reporting-Services#140]
I can't seem to find how the authorization suppose to work with the custom security extension?
I have almost done with the authentication now how I'm supposed to define the user access rights ?? ps: authenticate using an external service.

I can't find anything that can help me in the Rest APIs, how can I assign a user to a specific role? or can I still use AD groups with the extension?

Any ideas of what ways are available or point me to right documentation? I can see the SSRS tables and the stored procedures but not sure if this is possible to use?

**Comment by YvesR** [comment]
When you dig into it, it i quiet simple, but I agree it took me some time to find out.
Each catalog operation has its own `CheckAccess` method. So you need to implement this in your class.

Example of my implementation I did for one operation:

    public bool CheckAccess(
      string userName,
      IntPtr userToken,
      byte[] secDesc,
      ModelItemOperation modelItemOperation)
    {
      #region CHANGES FOR GROUPISM (ENABLING GROUPS)

      var informer = new InformerAuthentication();
      string actorName = informer.ActorName(userName);
      string[] str = informer.GetUserGroup(userName);

      #endregion

      if (IsAdminByDefault(actorName)) return true;

      AceCollection acl = DeserializeAcl(secDesc);
      foreach (AceStruct ace in acl)
      {
        // First check to see if the user or group has an access control 
        //  entry for the item

        /*     FOR GROUPS TO WHICH USER BELONGS
        ------------------------------------------------*/
        for (int i = 0; i < str.Length; i++)
        {
          if (0 == string.Compare(str[i], ace.PrincipalName, true,
                CultureInfo.CurrentCulture))
          {
            // If an entry is found, 
            // return true if the given required operation
            // is contained in the ACE structure
            foreach (ModelItemOperation aclOperation in ace.ModelItemOperations)
            {
              if (aclOperation == modelItemOperation)
                return true;
            }
          }
        }

        /*     FOR PARTICULAR USER 
        --------------------------------*/

        if (0 == string.Compare(actorName, ace.PrincipalName, true,
              CultureInfo.CurrentCulture))
        {
          // If an entry is found, 
          // return true if the given required operation
          // is contained in the ACE structure
          foreach (ModelItemOperation aclOperation in ace.ModelItemOperations)
          {
            if (aclOperation == modelItemOperation)
              return true;
          }
        }
      }

      return false;
    }

**Comment by Et3rnal** [comment]
What I end up doing, as I have some sort of Single Sign-On I change it to return current user role on my main application and use the role as "PrincipalName".
The problem I faced was maintaining the value inside CheckAccess() as httpcontext.current is null when calling from API's, so no session access, no cookies!. I have used a database but trying to avoid that however no luck so far.

Thanks for sharing the code, I think I can use it to improve my implementation

**Comment by YvesR** [comment]
Yes, I did check and you are right. So in this case as we have no session, no session cookies you need to implement this using a security token with each call. So you need to implement a call against API, authenticate, return a token. Each request must include token then and you need to implement a checkup against this valid token.

**Comment by Et3rnal** [comment]
I'm not able to get anything to CheckAccess(), actually to the whole class! I even noticed today that the session will expire even if I'm using it! (expire doesn't extend/renew). I do get a token as part of set-cookie header when I POST a session through the API which then gets used to validate other requests "I don't have to do that, SSRS take care of it I just pass `withCredentials: true` with my request. I have used database now as a session holder to maintain the other values I need inside CheckAccess() after failing to implement a cache.

**Comment by nickQuant** [comment]
Hi YvesR 

> When you dig into it, it i quiet simple, but I agree it took me some time to find out.
> Each catalog operation has its own `CheckAccess` method. So you need to implement this in your class.
> 
> Example of my implementation I did for one operation:
> 
> ```

I think the problem with the implementation you presented in how the Authorisation settings are originally setup in the SSRS database.  When you are using custom authentication, the inbuilt screen in the SSRS portal for managing users and roles won't recognise any groups - they are built to work with AD groups and roles, and configure security off that.

From everything I've been able to work out, one you are doing custom authentication, you are totally on your own for how to manage authorization too.

**Comment by YvesR** [comment]
> From everything I've been able to work out, one you are doing custom authentication, you are totally on your own for how to manage authorization too.

Exactly, that is why I did this my own as you can see in `string[] str = informer.GetUserGroup(userName);` I did create a list of groups, SSRS just "name-compare" them, so it is on your own but not a big issue todo so.

**Comment by tgorgul** [comment]
> > From everything I've been able to work out, one you are doing custom authentication, you are totally on your own for how to manage authorization too.
> 
> Exactly, that is why I did this my own as you can see in `string[] str = informer.GetUserGroup(userName);` I did create a list of groups, SSRS just "name-compare" them, so it is on your own but not a big issue todo so.

Hi! Could you explain how ssrs knows about user groups? I mean custom groups. Not AD. How can I add users to group? When method CheckAccess() called I just had rights for user. Am I right than `string[] str = informer.GetUserGroup(userName);` it is your custom groups? But I don't understand how rights for groups appeared in secDesc.

**Comment by YvesR** [comment]
> Hi! Could you explain how ssrs knows about user groups? I mean custom groups. Not AD. How can I add users to group? When method CheckAccess() called I just had rights for user. Am I right than `string[] str = informer.GetUserGroup(userName);` it is your custom groups? But I don't understand how rights for groups appeared in secDesc. Is secDesc contains all permissions for all users and groups? Not only for current user?

One thing you have to understand about SSRS authorization. Each actor will be a record with its own unique key. If you authorize actors to reports, or grant anything else you work with those unique keys. All Actors are stored in `Users`, regardless if it is a user or a group or whatever.
Also the names are written in clear text in column `UserName`.

So a actor that represents one of your custom groups will be there also.
Assume your group's name is `myCustomGroup` you would authorize for folder or report access to `myCustomGroup` using the report server UI.

Knowing this next step is pretty simple:
`string[] str = informer.GetUserGroup(userName);` returns a array of the groups for my user from my backend as clear text. Inside `CheckAccess` methods you simple string compare those names in an iteration against your principal name of the acl collection. An example I did already post above.
