### ISSUE TITLE
logout doesn't work if authenticated through form

### ISSUE THREAD

**Issue by Et3rnal** [microsoft/Reporting-Services#141]
**SSRS 2017**
For example: If you send a GET request to get the current user
`GET /me`
and you don't have a current session, then an "Authentication Required" popup will appear asking for username and password
![ar](https://user-images.githubusercontent.com/441522/54725901-ab39b280-4bc0-11e9-9a2a-e7347966839d.png)

So far that all good, the problem is the session that gets created by filling the popup cannot be destroyed "logout" through the API
`DELETE /Session`

Is this a bug? if not how can I terminate that session?

**Comment by Et3rnal** [comment]
I need a way to disable this form authentication popup? at least for APIs only?

**Comment by gboreki** [comment]
This sounds like a behavior of your browser, if you hit the portal e.g. /reports endpoint from the browser you are redirected to the logon page, the authentication there is based on cookie and logout happens by issue an empty cookie. This is the typical flow for a user visiting SSRS when running with custom authentication.

When instyead you hit the api directly (like /me above), you got a BASIC auth prompt, that prompt is from your browser and is sent through a header, the browser is caching and sending the user+pwd in subsequent requests.

**Comment by Et3rnal** [comment]
Thanks,

So it's all browser behaviour, does SSRS or the extension provide a way to avoid that so we handle 401 through the code? or even change the returned 401 to something else to prevent this behaviour?

**Comment by Et3rnal** [comment]
In order to avoid the browser, the SSRS response needs to be altered to remove/rename the challenge in the `WWW-Authenticate` header which doesn't seem to be possible so far.

The current response is:
```WWW-Authenticate | Basic Realm=""```

**Comment by gboreki** [comment]
Do you mind describing your full scenario? How are you hosting the app and authenticating to ssrs?

**Comment by Et3rnal** [comment]
I'm using this extension to implement my custom authentication, then using REST to communicate with SSRS, login, get a list of reports and if the user clicks on one of the reports in opens using the embedded approach.

Now there are other parts in the app beside reports and sometimes the user gets to reports page after SSRS session has already expired this is when the user will get 401 with the popup this is isn't too bad.
The other case if the user wants to logout but SSRS has already expired as it doesn't renew/extend the session even if it is in use! then my app sends a request to SSRS to delete the session which doesn't exist but the user will be asked to log in again with the browser popup.

I don't see the new to challenge the browser to do basic authentication with APIs or at least allow a way to change that `Basic` in the `http.sys` to something else to avoid the browser behaviour.

**Comment by Et3rnal** [comment]
I'm working again on the extension and I would like to see if this is possible now

I would like to modify the header in the response `WWW-Authenticate` from
`WWW-Authenticate: Basic realm=""`
to
`WWW-Authenticate: xBasic realm=""`

Changing the word from Basic to anything else will stop the browser's behaviour.
