### ISSUE TITLE
Access session cookie in Authorization.cs

### ISSUE THREAD

**Issue by Et3rnal** [microsoft/Reporting-Services#142]
I'm trying to pass some extra details I need to help me with CheckAccess and I can't find a way to preserve the values I'm getting through the authentication process (other than storing it in a database!)
I know SSRS allow us to identify PassThrough Cookies but how? I can't pass any cookies??

Not to mention that "HttpContext.Current" is always null inside  Authorization.cs ? so how to get any values inside this class other than using database (or is it the only way?)

**Comment by Et3rnal** [comment]
This problem appears to be with Restful APIs only, accessing SSRS through /ReportServer has httpContext.Current unlike using the API endpoints or the login page through the /reports url (web portal URL)

Is this a bug ?

**Comment by CH-AF** [comment]
@Et3rnal Did you manage to find a work-around for this ? I'm currently stuck in the Authorization part since I can't access HttpContext to read the querystring of the request

**Comment by Et3rnal** [comment]
Unfortunately no, I give up and used database

**Comment by CH-AF** [comment]
Okay, thank you for replying.
I have a similar solution but with a cache instead

**Comment by Et3rnal** [comment]
@CH-AF May I know how did you do it with cache? where did you cache it? and how did you access the cache from the extension and your app as well? 

Are you using rest APIs?

**Comment by CH-AF** [comment]
I created my own static cache class, that implements System.Runtime.Caching.MemoryCache (https://docs.microsoft.com/en-us/dotnet/api/system.runtime.caching.memorycache?view=netframework-4.8), which I call from the IAuthenticationExtension2 and IAuthorizationExtension implementations.

I do make calls to an API to fetch other information needed to verify that the value should be cached, but that is separate so technically I'm not using a rest API for the cache.
