### ISSUE TITLE
Unexpected error encountered when edit report in PowerBI Report Server

### ISSUE THREAD

**Issue by metinsevindik** [Microsoft/Reporting-Services#143]
Hi;

I am using Report Server Custom Authentication. Everything running. But I  taked "Unexpected error encountered" when edit report in PowerBI Report Server.
![edit report](https://user-images.githubusercontent.com/4583684/55074630-d8df9980-50a1-11e9-90fb-d5dcb91797d9.PNG)

![unexpected error](https://user-images.githubusercontent.com/4583684/55074537-9ddd6600-50a1-11e9-87af-c493957c8f5e.PNG)

Also can not save as to PowerBI Report Server
![Ekran Alıntısı](https://user-images.githubusercontent.com/4583684/55074781-41c71180-50a2-11e9-9a23-6d2743428b69.PNG)

Thank you. Good reporting.

**Comment by jtarquino** [comment]
Power BI Desktop don't support custom authentication, you need to use the portal for upload of Power BI Desktop reports

**Comment by yls087412** [comment]
可以考虑扩展部署方案，一个站点Windows认证，用于desktop的开发部署；一个站点用自定义验证，用于嵌入到业务站点。
