### ISSUE TITLE
Logging capability

### ISSUE THREAD

**Issue by Et3rnal** [microsoft/Reporting-Services#151]
Has anyone worked out how to add his own logging? What did you use how to configure it. I have tried log4net and NLog without luck

With log4Net as soon as I add the configuration the login page doesn't load anymore and NLog after installing it throws exceptions when I try login however I can't debug as well!

**Comment by jtarquino** [comment]
I would recommend to post your question in the https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlreportingservices so the community can help you or contact support.
This project only covers questions about the samples
