### ISSUE TITLE
Customdata() is invalid after the new version of 2019 configures SSRS + SSAS

### ISSUE THREAD

**Issue by ZIforever** [microsoft/Reporting-Services#153]
It is possible to configure SSRS + SSAS in the August 2018 version, but not in the 2019 version. Same configuration, different versions.
![image](https://user-images.githubusercontent.com/42140830/65004596-918ae500-d92f-11e9-9797-a51bdcaaa70d.png)

**Comment by gboreki** [comment]
Can you clarify what is the change in behavior? Also, is this an issue with Custom Authentication or in general? But since this sounds like a change in behavior of the product I suggest to post it to the report server forum: https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer

**Comment by ZIforever** [comment]
> Can you clarify what is the change in behavior? Also, is this an issue with Custom Authentication or in general? But since this sounds like a change in behavior of the product I suggest to post it to the report server forum: https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer

hi:
This problem will occur when the user-defined identity authentication is adopted, and it is after the version of SSRs is greater than that of January 2019.
