### ISSUE TITLE
Row level security error in custom security

### ISSUE THREAD

**Issue by f14eagle** [microsoft/Reporting-Services#155]
Hi, I've followed the steps to enable custom security in our reporting server, everything works fine, including user and group security authentication and authorization.

The only problem is the row-level security in the report. The row-level security works when we grant the role to a single user, but if we grant the role to a group, it doesn't at all.

I checked the log file and find there is a Microsoft.PowerBI.ReportServer.WebApi.ASConnection.RlsNotAuthorizedForModelException. And there is no related function in Authorization.cs file to handle such authorization logic for RLS.

Could you please help us with this?

Thank you in advance.

**Comment by gboreki** [comment]
Unfortunately, the interfaces used for Custom Authentication don't support group resolution. Feel free to add an item to ideas.powerbi.com for this to be considered for a future release:
https://ideas.powerbi.com/forums/265200-power-bi-ideas
