### ISSUE TITLE
Power BI Report Server Custom Authentication: IIS that host the webpage and PBIRS in different machines

### ISSUE THREAD

**Issue by glhl** [microsoft/Reporting-Services#156]
I am trying to do custom authentication in my solution that will use Power BI Report Server. The user will see the report through an IFrame pointing to the Report hosted in PBIRS. We want to use CustomAuthentication, only user logged in the site will see the report.

Is It possible to the IIS that will host my Asp page and the PBIRS are in different machines? Or they need to be in the same machine?

I think is not possible, because I read in a forum said that the IIS web.config and the PBIRS web.config need to have the same machine keys; but I need confirmation.

Thank You

**Comment by gboreki** [comment]
There is no requirement that they be in the same machine, it all depends on the design/topology that you choose for your application. If they are in different machines and you set the same machineKey for both services, they will be able to issue the same security cookies (e.g. a user who signs in to PBIRS would be able to navigate authenticated to your site), this might be undesired. You can also build a service to service chanel and from your authentication Extension in PBIRS call into your service to authenticate the user.

**Comment by glhl** [comment]
@gboreki 

Thank You for your answer. In my environment, the IIS that hosts the site have machine key configured as 'AutoGenerate, IsolateApps', and the ReportServer is hosted in another machine( VM clone ), with a random machine key in ReportServer and are working fine. Is this right?

But now I have another problem. When I install the ReportServer in a new machine that doesn't have a IIS configured, I'm having machine key problem. After that I tried to create a machine for ReportServer with a IIS configured by myself( AutoGenerate, IsolateApps too ), and the machine key problem still appear.

Scenario 1:
SiteMachine ( IIS machinekey 'AutoGenerate, IsolateApps' ) -> ReportServerMachine ( IIS machinekey 'AutoGenerate, IsolateApps' ) ( MachineB is a old VM clone from MachineA )- WORK FINE

Scenario 2:
SiteMachine ( IIS machinekey 'AutoGenerate, IsolateApps' ) -> ReportServerMachine ( ReportServer: Without IIS instaled) - Doesn't work because machine key problem

Scenario 3:
SiteMachine ( IIS machinekey 'AutoGenerate, IsolateApps' ) -> ReportServerMachine ( ReportServer: IIS configured by myself 'AutoGenerate, IsolateApps' trying to imitate IIS of SiteMachine configuration ) - Doesn't work because machine key problem


Do you know what kind of IIS configuration that can be causing this machine key problem?? The configuration of ReportServer in the three scenarios are the same, including same machine key.
I'm not the site developer/responsible, the site is old and is another team, so the SiteMachine has been around for many years

**Comment by metinsevindik** [comment]
Hi @glhl,
We developed a sharepoint web part same your issue.
We system info
- [PowerBI Report Server Custom Security](https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample)

Steps
1- We changed some code in Logon.aspx to login with token
2- Development a Sharepoint Webpart for report viewer in iframe . 
This webpart include parameters 
 **Param1**: report server logon page url, 
 **Param2**: PowerBI Report URL,
 **Param3**: open report by username

if you want, I can share to my all project.
Write by dm for details

**Comment by Soheil65** [comment]
> iframe
Hi @metinsevindik ,
I tried with iframe but I faced to a problem.
When I did authenticate then  redirected to login page again 

Thanks if anyone can help me

**Comment by Soheil65** [comment]
> Hi @glhl,
> We developed a sharepoint web part same your issue.
> We system info
> 
> * [PowerBI Report Server Custom Security](https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample)
> 
> Steps
> 1- We changed some code in Logon.aspx to login with token
> 2- Development a Sharepoint Webpart for report viewer in iframe .
> This webpart include parameters
> **Param1**: report server logon page url,
> **Param2**: PowerBI Report URL,
> **Param3**: open report by username
> 
> if you want, I can share to my all project.
> Write by dm for details



I tried with iframe but I faced to a problem.
When I did authenticate then redirected to login page again

Thanks if anyone can help me

**Comment by NITRO-AN515-54** [comment]
@Soheil65 @metinsevindik @gboreki @glhl

The same goes here did anyone find any solution? After implementing custom authentication I am not able to open reports in the iframe. If I open the report server URL directly without an iframe it works fine.

https://stackoverflow.com/questions/75795292/power-bi-reporting-server-custom-authentication-iframe-error?noredirect=1#comment133705253_75795292
