### ISSUE TITLE
Reduce the PBIRS main page session timeout

### ISSUE THREAD

**Issue by glhl** [microsoft/Reporting-Services#158]
Hi

I have a site that has an iframe that connect in PBIRS using CustomAuthentication. My Custom Authentication uses the UserInformation stored in Database to do Custom Authentication. 
When I am authenticated on the site, I can open the 'http://.../Reports/Browse' in another tab. The problem is that after I do log out/close my site, I want to block the 'http://.../Reports/Browse' from the user. This access remains open to the user for more than 30 minutes after the ReportServer block the session.

---Before login in my site----
http://...../Reports/browser: access blocked

------After login in my site and custom authentication in PBIRS----
http://...../Reports/browser: access open for MySiteUser

------After logout in my site/close the page that call ReportServer----
http://...../Reports/browser: access remains open for MySiteUser

------More than 30 minutes after close the page----
http://...../Reports/browser: access blocked again

There is an entrance in web.config or rsreportserver.config that can help me to reduce this session time to close 1 minute at least after I close my site? I already tried the sessionState tag in the Web.config, but not resolved.

Thank You

**Comment by glhl** [comment]
I tried to resolve this problem reducing the 'timeout' value in the web.config section 'loginurl="logon.aspx" name="sqlAuthCookie", timeout="1"'....but now I have another problem, always the user has his access blocked in ReportPage/browse and in the iframe too after 1 minute, even when the user is manipulating the report in the Iframe.

This is not what I want, I want that my access in the http://.../Reports/browse be blocked after 1 minute of inactivity, only inactivity.

**Comment by gboreki** [comment]
Have you tried using sliding expiration? https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.slidingexpiration

sliding expiration should reissue the cookie after half of the time passed, but the customer is still actively using it, you probably want to set it longer than a minute, maybe 10 minutes?

**Comment by glhl** [comment]
@gboreki . Thank You!!!
This solved my problem!!
