### ISSUE TITLE
IntPtr UserId usage and meaning

### ISSUE THREAD

**Issue by samusaran** [microsoft/Reporting-Services#159]
In `GetUserInfo`, what is `out IntPtr userId` used for?

I always see that set to `IntPtr.Zero`, but is it actually used for something?

If not, why is it there?

**Comment by gboreki** [comment]
That is something your authentication extension might use. You return it as part of GetUserInfo and ssrs will send the same values to the calls of the AutorizationExtension: https://docs.microsoft.com/en-us/dotnet/api/microsoft.reportingservices.interfaces.iauthorizationextension?view=sqlserver-2016
