### ISSUE TITLE
SSRS returns a 503

### ISSUE THREAD

**Issue by gmcfarlane** [microsoft/Reporting-Services#160]
I followed the instructions to the best of my ability... getting a 503. 
Any suggestions for logs i might consult? 

https://docs.microsoft.com/en-us/sql/reporting-services/report-server/reporting-services-log-files-and-sources?view=sql-server-ver15

Looking through this and yet to find a 503 error and explanation. 
I can uninstall/re-install SSRS , but that doesnt sound like an efficient debug cycle. 

Any hints/suggestions would be appreciated

**Comment by jtarquino** [comment]
Is probably some issue in your configuration, your best option is to setup a clean machine with the automatic configuration sample (https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample#automatic-configuration-of-the-sample) and then compare the config files with the environment where you are having issues
