### ISSUE TITLE
PBIRS v.15.0.1102.371

### ISSUE THREAD

**Issue by InnoChrR** [microsoft/Reporting-Services#161]
I tried your Auth excample and it works until i will switch to /reports - there is an issue on Portal app
Exception: System.Web.HttpException (0x80004005): Unable to validate data.
   at System.Web.Configuration.MachineKeySection.EncryptOrDecryptDat

first I had try to add machinekey in rsreportserver.config (followed by your description) - the other web.config and machine Config of .net i added later
do have an hint for me?

Thanks Christian

**Comment by jtarquino** [comment]
Is probably some issue in your configuration, your best option is to setup a clean machine with the automatic configuration sample (https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample#automatic-configuration-of-the-sample) and then compare the config files with the environment where you are having issues

**Comment by InnoChrR** [comment]
Thanks Jaime. Yes, i had done this by your powershell script. Is there another way to set machinekeys or make it as part of your VS solution?
