### ISSUE TITLE
OAuth Authentication usage/documentation

### ISSUE THREAD

**Issue by alex-lucid** [microsoft/Reporting-Services#165]
I found that there is an AADAuthenticationExtension Security extension and OAuth Authentication type available in SSRS 2017.
Though there is no mention about this in documentation or blogs.
Is there any way to use it for Authentication for SSRS Portal and Azure AD v2 endpoint ?
If yes, **please guide what settings I should put in my configs?**

From extracted source code I figured that rsreportserve.config file must have section like below:

`<OAuthConnectionConfiguration>
		<OAuthClientId></OAuthClientId>
		<OAuthClientSecret></OAuthClientSecret>
		<OAuthTenant></OAuthTenant>
		<OAuthTokenUrl></OAuthTokenUrl>
		<OAuthAuthorizationUrl></OAuthAuthorizationUrl>
		<OAuthFederationMetadataUrl></OAuthFederationMetadataUrl>
		<OAuthResourceUrl></OAuthResourceUrl>
		<OAuthNativeClientId></OAuthNativeClientId>
		<OAuthGraphUrl></OAuthGraphUrl>
		<OAuthSessionCookieName></OAuthSessionCookieName>
		<OAuthLogoutUrl></OAuthLogoutUrl>
	</OAuthConnectionConfiguration>`

then 

`<Authentication>
		<AuthenticationTypes>
			<OAuth/>
		</AuthenticationTypes>
		<RSWindowsExtendedProtectionLevel>Off</RSWindowsExtendedProtectionLevel>
		<RSWindowsExtendedProtectionScenario>Proxy</RSWindowsExtendedProtectionScenario>
		<EnableAuthPersistence>true</EnableAuthPersistence>
	</Authentication>`

and finally

`<Extensions>
<Authentication>
			<Extension Name="OAuth" Type="Microsoft.ReportingServices.Authentication.AADAuthenticationExtension, Microsoft.ReportingServices.Authorization"/>
		</Authentication></Extensions>`

But I am only getting NullReference exception from 
`Microsoft.ReportingServices.Portal.Services.Configuration.OAuthClientConfigurationService.GetConfigInfoScript()`
looks like settings are not read correctly:
((IPortalConfigurationManager)_portalConfigurationManager).Current.OAuthConfiguration is null

**Comment by jtarquino** [comment]
It is not a supported scenario

**Comment by alex-lucid** [comment]
> It is not a supported scenario

Probably some samples in your tests? ;)

**Comment by jtarquino** [comment]
It's not a completed feature, missing among many other things the ability to configure it, in its current state its even unlikely to work at all

**Comment by alex-lucid** [comment]
Hello again :) 
True, though I see it is fully working middleware that just needs correct configuration values and token from the outside.

I was able to inject configuration and add an html page into the ReportServer's host to use MSAL.js to get a token

Client_Id/tenant/redirecturl/resourceurl are same on client that gets a token and middleware that validates it.

But it issues

IDX10501: Signature validation failed. Unable to match key: 
kid: 'piVlloQDSMKxh1m2ygqGSVdgFpA'.

at 
`GetUserInfo(out IIdentity userIdentity, out IntPtr userId) -> ResolveBearer->_tokenHandler.ValidateToken()`

of the AADAuthenticationExtension's code

My MSAL .js config for token:

`var msalConfig = {
        auth: {
            clientId: '**GUID1**', //This is your client ID
            authority: "https://login.microsoftonline.com/**MYTENANT**/v2.0" 
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        }
    };`

and my OAuth config for AADAuthenticationExtension

`<Authentication>
  <Extension Name="OAuth" Type="Microsoft.ReportingServices.Authentication.AADAuthenticationExtension,Microsoft.ReportingServices.Authorization">
  <Configuration>
	<OAuth>
		<OAuthClientId>**GUID1**</OAuthClientId>
		<OAuthNativeClientId>**GUID1**</OAuthNativeClientId>
		<OAuthFederationMetadataUrl>https://login.microsoftonline.com/**MYTENANT**/federationmetadata/2007-06/federationmetadata.xml</OAuthFederationMetadataUrl>
		<OAuthAuthorizationUrl>https://login.microsoftonline.com/**MYTENANT**/oauth2/v2.0/authorize</OAuthAuthorizationUrl>
		<OAuthResourceUrl>http://localhost/ReportServer/</OAuthResourceUrl>
		<OAuthTokenUrl>https://login.microsoftonline.com/**MYTENANT**/oauth2/v2.0/token</OAuthTokenUrl>
		<OAuthClientSecret>**MYCLIENTSECRET**</OAuthClientSecret>
		<OAuthTenant>**MYTENANT**</OAuthTenant>
		<OAuthGraphUrl>https://graph.microsoft.com</OAuthGraphUrl>
		<OAuthSessionCookieName>SSRSOAuthSession</OAuthSessionCookieName>
		<OAuthLogoutUrl>https://login.microsoftonline.com/**MYTENANT**/saml2</OAuthLogoutUrl>
	</OAuth>
  </Configuration>
  </Extension>
</Authentication>`

MYTENANT is a GUID of my tenant
GUID1 is just a ClientID

Please advise what may bring up that error regarding IDX10501, invalid keys?
Many thanks in advance!
