### ISSUE TITLE
CORS Error using mssql-ssrs

### ISSUE THREAD

**Issue by Subashree01** [microsoft/Reporting-Services#168]
I have used mssql-ssrs in react js to generate the report 

```
   const serverUrl = 'http://10.10.11.130/evo2sql01reportserver';
        ssrs.setServerUrl(serverUrl);
        const reportPath='Evolution/QA/SupplierPerformanceReport';
        const fileType='PDF';
        const auth = {
            username: '****',
            password: '****',
            workstation: '', // optional
            domain: '', // optional
          };
      await ssrs.reportExecution.getReportByUrl(reportPath, fileType, this.excelDatas, auth);
```
Using the above syntax i am hitting the reporting service to fetch the Specific Report.

But i get the below CORS error, 

`Access to fetch at 'http://10.10.11.130/evo2sql01reportserver?/Evolution/QA/SupplierPerformanceReport&rs:Command=Render&rs:Format=PDF' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Kindly Suggest a way to add the CORS headers with/without modifying node modules.

**Comment by gboreki** [comment]
CORS need to be configured in your report server, the doc below describe which properties to change:
https://docs.microsoft.com/en-us/sql/reporting-services/tools/server-properties-advanced-page-reporting-services?view=sql-server-2017
