### ISSUE TITLE
Database Connection String

### ISSUE THREAD

**Issue by kswier** [microsoft/Reporting-Services#170]
I would like to add a database connection string to a config file.  However, I am not sure which config file to add it to.  I have tried web.config and rsreportserver.config.  Each config file has its short comings, the database connection string isn't always available.  Where it the best place to put a database connection string?

**Comment by vpratti** [comment]
@kswier Did you figure this out. I am at the same point as you were last time.

**Comment by kswier** [comment]
I am still having issues.  The security extension will use the xxx.dll.config file where xxx is the name of your security extension.  However, it looks like the config file can't be accessed when the security extension starts the authorization.  Which has me puzzled.

**Comment by kswier** [comment]
@vpratti what I ended up doing is put the database connection string in the rsreportserver.config file.  I put it in the AdminConfiguration section that is also used for the security extension's admin login.  Then in the Authorization.cs file I added getting the connection string to the SetConfiguration method.  

This is not the most elegant way to do this, but it was the only solution I found to make it work.

**Comment by gboreki** [comment]
The recommendation is to have a configuration file specific for your extension as opposed to attempt using one from reportserver. 

In order for your security extension to have access to the file you need to provide access to the reportserver account you also need to give permissions for the extension dll in the rspolicy as described here:
https://docs.microsoft.com/en-us/sql/reporting-services/extensions/secure-development/using-reporting-services-security-policy-files?view=sql-server-ver15
