### ISSUE TITLE
Make sure that it is compiled before accessing the page

### ISSUE THREAD

**Issue by snemirovskyatma** [microsoft/Reporting-Services#171]
Hello All,

I used the CustomSecurity sample successfully on my local machine compiling it in VS 2019 and deploying on PBIRS 2019. But when I tried to copy the DLLs to PBIRS on a different machine I get the following error:

webserver!ReportServer_0-1!4932c!03/30/2020-14:29:31:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: , Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: The report server encountered an unhandled exception in HttpApplication. ---> System.Web.HttpParseException: Could not load the assembly 'Microsoft.Samples.ReportingServices.CustomSecurity'. Make sure that it is compiled before accessing the page. ---> System.Web.HttpParseException: Could not load the assembly 'Microsoft.Samples.ReportingServices.CustomSecurity'. Make sure that it is compiled before accessing the page. ---> System.Web.HttpException: Could not load the assembly 'Microsoft.Samples.ReportingServices.CustomSecurity'. Make sure that it is compiled before accessing the page.

The DLLs were copied to the same folders (Portal, PowerBI, ReportServer\bin) and the same edits were made to all three config files as outlined in the README. 

Please advise what else I may be missing.

Thank you!

**Comment by Kingslayerz** [comment]
@snemirovskyatma hey! how did you get rid of this error? I'm also facing the same issue.. would be helpful if you share the solution! Thanks!
