### ISSUE TITLE
IRSRequestContext  is not found in the namespace and assembly

### ISSUE THREAD

**Issue by karthiktanj** [microsoft/Reporting-Services#176]
The below code is not working the same issue showing the namespace and assembly not found for the interface IRSRequestContext  . Could you please provide the fix

 //adding new GetUserInfo method for IAuthenticationExtension2
        public void GetUserInfo(IRSRequestContext requestContext, out IIdentity userIdentity, out IntPtr userId)
        {
            userIdentity = null;
            if (requestContext.User != null)
            {
                userIdentity = requestContext.User;
            }

            // initialize a pointer to the current user id to zero
            userId = IntPtr.Zero;
        }

**Comment by cfitzg** [comment]
Same answer as Issue #177 - you just need to make sure you reference the assembly containing the namespace in which "IRSRequestContext" resides: C:\Program Files\Microsoft SQL Server Reporting Services\SSRS\ReportServer\bin\Microsoft.ReportingServices.Interfaces.dll

**Comment by gboreki** [comment]
See reply by cfitzg
