### ISSUE TITLE
IAuthenticationExtension2  namespace and assembly not found

### ISSUE THREAD

**Issue by karthiktanj** [microsoft/Reporting-Services#177]
After installing the Microsoft.Reporting.Interfaces the IAuthenticationExtension2 is showing error not able to find the name. After Checking in the Reporting Interface IAuthenticationExtension2 is not avaliable. Could you please provide the fix for this issue.

**Comment by cfitzg** [comment]
Yeah it'd be nice if it recognized it right away or put it on the PATH var.

You have 2 options:

1). (recommended only if you are using Web Forms and the WebForm-based, report viewer control)

You can install the Nuget Package, "Microsoft.ReportingServices.ReportViewerControl.WebForms" 

![image](https://user-images.githubusercontent.com/21161982/82939925-a8231a80-9f59-11ea-9ad5-91a057476be8.png)


2). (recommended, clean approach if you are not using web forms):

Manually add a reference to the Microsoft.Reporting.Interfaces in your project. The file is located/installed here when you install SSRS:

![image](https://user-images.githubusercontent.com/21161982/82940478-84ac9f80-9f5a-11ea-891b-d9796b2b295d.png)

**Comment by gboreki** [comment]
The assembly is not provide as part of the sample, it is deployed as part of the server and only servers from version 2016 and above will have IRSRequestContext (assemblies from previous versions will run in backwards compatibility mode). As cfitzg  pointed above, you should reference/copy it from the server path.
