### ISSUE TITLE
Error on entering username/pwd on logon.aspx

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services#18]
I was able to land on logon.aspx page; which contains below interface
User Name : TextBox
Password: TextBox
Button for Register User
Button for Logon User
When i click on either button i end up with below error
'System.Data.SqlClient.SqlClientPermission, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

**Comment by jtarquino** [comment]
Double check all the changes in the RSSrvPolicy.config file
