### ISSUE TITLE
How to register admin user

### ISSUE THREAD

**Issue by Wiibroe14** [microsoft/Reporting-Services#181]
Hi,

I just installed the Custom Security extension on my Power BI Report Server
I registered through the web page into the UserAccounts database but I don't know how I can add the first admin user (no ActiveDirectory) in the internal Report Server database.

Could you please help me with this?

Thank you in advance.

**Comment by gboreki** [comment]
In the sample, the admin account is initially defined in the config files (there is an element for adminUser), the extension gives super user to that account. In the end, this will vary depending on your implementation, if you custom extension already have properties that indicate when a user is admin in the external repository, then you can use those to resolve it.

Let me know if this addresses your problem.

Thanks
Boreki
