### ISSUE TITLE
Microsoft Report Builder raised exception if ALT+ENTER keys are pressed at the same time

### ISSUE THREAD

**Issue by asdf913** [microsoft/Reporting-Services#182]
The below is the exception found in the exception dialog.

PS since my desktop Windows locale is to Tradition Chinese, so the exception message contains Traditional Chinese Character(s).

![image](https://user-images.githubusercontent.com/2301325/83841716-fabbbe00-a733-11ea-8276-f12ffe8fdb47.png)

`如需叫用 Just-In-Time (JIT) 偵錯的詳細資料，
請參閱本訊息結尾處 (而非這個對話方塊) 的資訊。

************** 例外狀況文字 **************
System.ArgumentNullException: 值不能為 null。
參數名稱: culture
   於 System.Char.ToUpper(Char c, CultureInfo culture)
   於 Microsoft.ReportDesigner.Office12Ribbon.MainForm.WndProc(Message& m)
   於 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   於 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   於 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 已載入的組件 **************
mscorlib
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3468.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
MSReportBuilder
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/MSReportBuilder.exe
----------------------------------------
System.Windows.Forms
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3515.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3451.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3570.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.ReportingServices.ReportDesign.Forms
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.ReportDesign.Forms.DLL
----------------------------------------
Microsoft.ReportingServices.Designer.Controls
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.Designer.Controls.DLL
----------------------------------------
System.Configuration
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3324.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Microsoft.ReportingServices.ReportDesign.Common
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.ReportDesign.Common.DLL
----------------------------------------
System.Web
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3535.0 built by: NET472REL1LAST
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Xml
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.ReportingServices.RsClient
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.RsClient.DLL
----------------------------------------
Microsoft.ReportingServices.Designer.RdlDowngrade
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.Designer.RdlDowngrade.DLL
----------------------------------------
Microsoft.Data.ConnectionUI.Dialog
    組件版本: 10.0.0.0
    Win32 版本: 10.0.30319.1 built by: RTMRel
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.Data.ConnectionUI.Dialog.DLL
----------------------------------------
Microsoft.ReportingServices.QueryDesigners
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.QueryDesigners.DLL
----------------------------------------
Microsoft.ReportingServices.Diagnostics
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.Diagnostics.DLL
----------------------------------------
Microsoft.ReportBuilder.Telemetry
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportBuilder.Telemetry.DLL
----------------------------------------
Microsoft.ApplicationInsights
    組件版本: 2.9.1.0
    Win32 版本: 2.9.1.26108
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ApplicationInsights.DLL
----------------------------------------
Accessibility
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Microsoft.SqlServer.MgdSqlDumper
    組件版本: 15.0.0.0
    Win32 版本: 2018.0150.1300.48 ((SQLServer).190123-1320)
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.SqlServer.MgdSqlDumper.DLL
----------------------------------------
Microsoft.ReportingServices.Interfaces
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.Interfaces.DLL
----------------------------------------
mscorlib.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    組件版本: 1.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    組件版本: 1.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    組件版本: 1.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    組件版本: 1.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Design
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
Microsoft.DataWarehouse.RS
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.DataWarehouse.RS.DLL
----------------------------------------
Microsoft.DataWarehouse.Interfaces
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.DataWarehouse.Interfaces.DLL
----------------------------------------
Microsoft.ReportingServices.ComponentLibrary.Controls
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.ComponentLibrary.Controls.DLL
----------------------------------------
PresentationFramework
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3570.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3570.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3570.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3570.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Windows.Forms.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
WindowsFormsIntegration
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------
PresentationFramework.Classic
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.classic/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.classic.dll
----------------------------------------
PresentationFramework.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.resources/v4.0_4.0.0.0_zh-Hant_31bf3856ad364e35/PresentationFramework.resources.dll
----------------------------------------
PresentationFramework-SystemXml
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
PresentationFramework-SystemCore
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemCore/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemCore.dll
----------------------------------------
Microsoft.ReportingServices.QueryDesigners.Extensions
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.QueryDesigners.Extensions.DLL
----------------------------------------
Microsoft.ReportingServices.ReportPreview
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.ReportPreview.DLL
----------------------------------------
Microsoft.ReportingServices.RichText
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.RichText.DLL
----------------------------------------
Microsoft.ReportingServices.RPLObjectModel
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.RPLObjectModel.DLL
----------------------------------------
Microsoft.ReportingServices.ProcessingCore
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.ProcessingCore.DLL
----------------------------------------
UIAutomationProvider
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3570.0 built by: NET472REL1LAST_B
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
System.Xml.Linq
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Management
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
System.Web.Services
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.GeneratedCode
    組件版本: 1.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3515.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.Data.ConnectionUI
    組件版本: 10.0.0.0
    Win32 版本: 10.0.40219.1 built by: SP1Rel
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.Data.ConnectionUI.DLL
----------------------------------------
System.Data.OracleClient
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data.OracleClient/v4.0_4.0.0.0__b77a5c561934e089/System.Data.OracleClient.dll
----------------------------------------
Microsoft.ReportingServices.DataExtensions
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.DataExtensions.DLL
----------------------------------------
System.Numerics
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.Data.resources.dll
----------------------------------------
Microsoft.AnalysisServices.AdomdClientUI
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.AnalysisServices.AdomdClientUI.DLL
----------------------------------------
Microsoft.AnalysisServices.AdomdClient
    組件版本: 18.0.1.0
    Win32 版本: 15.0.32.45
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.AnalysisServices.AdomdClient.DLL
----------------------------------------
Microsoft.ReportingServices.QueryDesigners.SharePoint
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.QueryDesigners.SharePoint.DLL
----------------------------------------
Microsoft.ReportingServices.QueryDesigners.Essbase
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.QueryDesigners.Essbase.DLL
----------------------------------------
Microsoft.ReportingServices.DataExtensions.XmlaClient
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.DataExtensions.XmlaClient.DLL
----------------------------------------
Microsoft.ReportingServices.QueryDesigners.SapBw
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.QueryDesigners.SapBw.DLL
----------------------------------------
System.resources
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hant_b77a5c561934e089/System.resources.dll
----------------------------------------
MDXQueryGenerator
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/MDXQueryGenerator.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    組件版本: 3.13.1.846
    Win32 版本: 3.13.30726.1855
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
System.Runtime
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Transactions
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Collections.Concurrent
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections.Concurrent/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.Concurrent.dll
----------------------------------------
System.Reflection
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Globalization
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.IO
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll
----------------------------------------
System.Text.RegularExpressions
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Text.RegularExpressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.RegularExpressions.dll
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.Platform
    組件版本: 3.13.1.846
    Win32 版本: 3.13.30726.1855
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.DLL
----------------------------------------
System.Threading.Tasks
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
Newtonsoft.Json
    組件版本: 10.0.0.0
    Win32 版本: 10.0.3.21018
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.GeneratedCode
    組件版本: 1.0.0.0
    Win32 版本: 4.7.3221.0 built by: NET472REL1LAST_C
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.ReportingServices.SPBProcessing
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.SPBProcessing.DLL
----------------------------------------
Microsoft.ReportingServices.ImageRendering
    組件版本: 15.5.0.0
    Win32 版本: 15.0.1473.0
    程式碼庫: file:///C:/Program%20Files%20(x86)/Microsoft%20Report%20Builder/Microsoft.ReportingServices.ImageRendering.DLL
----------------------------------------
System.EnterpriseServices
    組件版本: 4.0.0.0
    Win32 版本: 4.7.3062.0 built by: NET472REL1
    程式碼庫: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

************** JIT 偵錯 **************
若要啟用 Just-In-Time (JIT) 偵錯功能，則必須在
此應用程式或電腦的 .config 檔案中，設定
system.windows.forms 區段內的 jitDebugging 值。
且該應用程式也必須在啟用偵錯的狀態下進行
編譯。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

當 JIT 偵錯功能啟用後，會將所有未處理的例外狀況
傳送給電腦上已註冊的 JIT 偵錯工具進行處
理，而不是使用這個對話方塊來處理。

`

**Comment by gboreki** [comment]
Thanks for reporting. This have been filed in our internal bug tracking for report builder and will be considered for a future release. We do not have an ETA at this point.
