### ISSUE TITLE
Support for Power BI Report Builder

### ISSUE THREAD

**Issue by guycurry** [microsoft/Reporting-Services#183]
Hi, Curious if custom data connectors are supported in Power BI Report Builder.  I've had success creating and using custom connectors within the Visual Studio application and deploying them to our SSRS and Power BI servers, but hoping I can explore the other report builder tools available for my team.

Thanks!

**Comment by gboreki** [comment]
Custom Data Connectors are not yet support in PowerBi Report Builder or in Power Bi Service (for paginated reports). I suggest that you vote or post that request in the powerbi ideas forum to help the prioritize community asks:
https://ideas.powerbi.com/forums/265200-power-bi-ideas?query=report%20builder

Thanks,
Boreki
