### ISSUE TITLE
RLS support in Custom Security Extension

### ISSUE THREAD

**Issue by rrrooommmaaa** [microsoft/Reporting-Services#188]
I have implemented a custom security extension based on the sample. It works ok, but when report is using RLS, I have to add users to the special report configuration tab: "Row-Level Security".
I couldn't find a way to circumvent this so that all users will gain access without explicitly specifying them.
I tried to add "Users" to that tab to specify a "user group" and IsValidPrincipal returns true for this name ("Users"), and CheckAccess returns true for all operations, still RLS is not working until I add that user's name explicitly.

**Comment by gboreki** [comment]
Unfortunately there is no way to handle groups in RLS in custom auth. I suggest that you enter a feature request in ideas.powerbi.com for consideration.

**Comment by eggeggss** [comment]
RLS group is still not work in custom auth ,so my solution is  pass the username in url to trigger the report's filter, although a little unsafe , but I embed the report url in iframe , hide the filter option and disable right click, It is difficult for normal people to discover this parameter from the URL 
sample is like this:

<iframe
src="https://xxx.xxx.xxx/reports/powerbi/myreport/auth_test?filter=query1/ename eq 'admin' &rs:embed=true">
</iframe>

database/column name

the full description is as follows:
https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters#special-characters-in-table-and-column-names

**Comment by tingtingli183** [comment]
> Unfortunately there is no way to handle groups in RLS in custom auth. I suggest that you enter a feature request in ideas.powerbi.com for consideration.

It's 2026 already, and it still can't be supported?
