### ISSUE TITLE
FormsAuthentication.RedirectFromLoginPage not working in Iframe

### ISSUE THREAD

**Issue by lotfi1008** [microsoft/Reporting-Services#189]
we override authentication for power bi report server and use this sample and every thing is working well but i need to embed my dashboards in asp.net core application (that use asp identity) with iframes and when i loading page for viewing dashboard, iframe show error

**desktop-jkskd96 redirected you too many times.**

in custom authentication that i installing on power BI report server , logging user is automatically with

`FormsAuthentication.RedirectFromLoginPage(username, false);`

every thing is OK when i load dashboard URL in browsers directly and user logged in automatically

but in Iframes i have problem

i testing with simple html file and still has problem

**Comment by jaulestiadefaria** [comment]
+1 on this. Any help/ideas are greatly appreciated!

Custom authentication works fine when accessing http://[server]/Reports/powerbi/[somereport]?rs:embed=true or  http://[server]/Reports

I am first redirected to logon page , once I enter credentials of a previously registered user it redirects fine.

This does not happen when http://[server]/Reports/powerbi/[somereport]?rs:embed=true or http://[server]/Reports
is the src of an iframe. i.e.  <iframe  src="http://[server]/Reports/powerbi/[somereport]?rs:embed=true" />

It is as if the authentication succeeds but something is missing, as it returns to back to the login:
![Screenshot 2020-11-18 104949](https://user-images.githubusercontent.com/21346956/99574169-decb7200-298b-11eb-82a4-1f560aa57c9f.png)


Thanks!

**Comment by cesczacks** [comment]
Same problem..
It seems to be IFrame did not accept `sqlAuthCookie`, so it redirects to the `login.aspx` again.
Appreciate if anyone can help to solve this.

**Comment by alextochetto** [comment]
If you are trying to use locally, create a URL in your hosts (file) like:
127.0.0.1       ssrs.local.com
It works for me but I didn't test it in a server.

**Comment by Soheil65** [comment]
I have the same problem when I want to embed report on iframe.
  error message :  127.0.0.1 redirected you too many times.

**Comment by Soheil65** [comment]
IFrame doesn't show report after click on login button.

**Comment by Soheil65** [comment]
IFrame doesn't show report when I clicked on login button

**Comment by alextochetto** [comment]
Another approach instead set a DNS it's about changing the URL in iframe like:
http://<ssrs server>/ReportServer/Pages/ReportViewer.aspx?<report name>&rs:Embed=true
This works for me with and without HTTPS in a development and production environments

**Comment by Soheil65** [comment]
> Another approach instead set a DNS it's about changing the URL in iframe like:
> http:///ReportServer/Pages/ReportViewer.aspx?&rs:Embed=true
> This works for me with and without HTTPS in a development and production environments

Please tell me more

**Comment by alextochetto** [comment]
> > Another approach instead set a DNS it's about changing the URL in iframe like:
> > http:///ReportServer/Pages/ReportViewer.aspx?&rs:Embed=true
> > This works for me with and without HTTPS in a development and production environments
> 
> Please tell me more

What's your really doubt?

**Comment by lemmax** [comment]
Hello lotfi1008!

This worked for me in Chrome and Edge using embedded HTML iframes:

1. Up-to-date .NET Framework using Windows built-in Check for updates (KB4524420 package required)
2. Add the following yellow parts to **c:\Program Files\Microsoft Power BI Report Server\PBIRS\ReportServer\web.config** file

![9fe36e26-ce1a-43d3-92b1-f9ef7604e232](https://user-images.githubusercontent.com/87125314/129634291-0f45730b-d1f5-4893-9109-19944ed9a883.png)

Best regards!

**Comment by Soheil65** [comment]
> Hello lotfi1008!
> 
> This worked for me in Chrome and Edge using embedded HTML iframes:
> 
> 1. Up-to-date .NET Framework using Windows built-in Check for updates (KB4524420 package required)
> 2. Add the following yellow parts to **c:\Program Files\Microsoft Power BI Report Server\PBIRS\ReportServer\web.config** file
> 
> ![9fe36e26-ce1a-43d3-92b1-f9ef7604e232](https://user-images.githubusercontent.com/87125314/129634291-0f45730b-d1f5-4893-9109-19944ed9a883.png)
> 
> This solution works only with HTTPS configuration!
> 
> Best regards!

Thank @lemmax,
I did it so I had to use an SSL certificate on power bi web service URL and  power bi web portal URL :-(
In your opinion can I do this without any SSL certificate

**Comment by jalvarezz** [comment]
> > Hello lotfi1008!
> > This worked for me in Chrome and Edge using embedded HTML iframes:
> > 
> > 1. Up-to-date .NET Framework using Windows built-in Check for updates (KB4524420 package required)
> > 2. Add the following yellow parts to **c:\Program Files\Microsoft Power BI Report Server\PBIRS\ReportServer\web.config** file
> > 
> > ![9fe36e26-ce1a-43d3-92b1-f9ef7604e232](https://user-images.githubusercontent.com/87125314/129634291-0f45730b-d1f5-4893-9109-19944ed9a883.png)
> > This solution works only with HTTPS configuration!
> > Best regards!
> 
> Thank @lemmax, I did it so I had to use an SSL certificate on power bi web service URL and power bi web portal URL :-( In your opinion can I do this without any SSL certificate

Generate a certificate using https://www.win-acme.com/ and use the requireSSL as explained above, restart service and works like a charm!

**Comment by lotfi1008** [comment]
thanks guys. I use secure cookie and using sub domain for power bi report server on ssl 
and problem solved. 
powerbi address : https://pbi.test.com
main application : https://test.com

**Comment by Manvish1230** [comment]
@lotfi1008 , Hi I am implementing similar approach, where i have to display SSRS reports using Form authentication.
 I got the form authentication working on SSRS side using a token and it works from Postman.

Now i need to send this token from Angular IFrame ,  can you please tell me how did you authenticate from iframe to SSRS? are you passing any parameter to the SSRS ?

Thanks

**Comment by Manvish1230** [comment]
@lotfi1008 , I am working on similar implementation
May i know, how did you configure sub domain for power bi? , did you install power BI on separate server?
