### ISSUE TITLE
Stuck  on Authorization/CheckAccess method

### ISSUE THREAD

**Issue by MSAGH** [microsoft/Reporting-Services#194]
Can someone please help, I want to give anyone who registers access to browse all the reports. I can currently register and logon a user, and I can logon as an admin user and access the reports, portal etc (as specified in the rsresportsserver.config AdminConfiguration element), but I don't know how to authorize any non admin users. What modifications do I make to the code for this to happen?

**Comment by gboreki** [comment]
You don't need to change the code of the sample for that, you just need to give the necessary permissions in the server to the items you want the users to see.

**Comment by MSAGH** [comment]
Thank you @gboreki I'm able to to this now.

**Comment by MSAGH** [comment]
Hi @gboreki 

This works perfectly when I manually add each registered user into the portal but as there will be thousands of users I want to update the Users and PolicyUserRole tables with a script.  I did this for one user ('user1' ) who has registered and successfully authenticated via the custom logon page but has not been added as a user into the portal, and when I run queries against this user and another user ('user2' ) who was added in via the portal, it shows that both users have the exact same permissions against the relevant report folder, reports and data sources.  

I then expected to see this first user ('user1' ) in the portal but this isn’t the case, and when logged in the user is not authorised to view the reports even though the query results show they have the required permissions.

When I manually added this user ('user1' ) into the portal, they could then access the reports.  This didn’t alter the data in the Users and PolicyUserRole tables.

Is there another table that needs updating?  Or is it not possible to add users this way?

Thanks

**Comment by MSAGH** [comment]
If I update the SecData table as well will this work?

**Comment by gboreki** [comment]
Making updates directly to the RS catalog its not supported since we do not document and the structure might change between updates. We do have APIs where you can set permissions to items, so you should instead script using SOAP or REST apis. We also have another project that wrap those APIs in powershell command-lets so that another option:
https://github.com/Microsoft/ReportingServicesTools you can see Grant-AccessOnCatalogItem for example.

**Comment by MSAGH** [comment]
Thank you @gboreki, I'll look into your suggestions.
