### ISSUE TITLE
How do i get the forms authentication sample interworking with power BI desktop

### ISSUE THREAD

**Issue by giantslogik** [microsoft/Reporting-Services#195]
the powerBI desktop just displays "Unexpected error occurred" when connecting to report server.
Report server is configured to use the custom "forms authentication" security extension.

**Comment by giantslogik** [comment]
Authentication extension is called
public void GetUserInfo(IRSRequestContext requestContext, out IIdentity userIdentity, out IntPtr userId)

Which doesn't allow anonymous access. But powerBI desktop doesn't show a logon form.

**Comment by jtarquino** [comment]
https://docs.microsoft.com/en-us/power-bi/report-server/install-powerbi-desktop
"Power BI Desktop optimized for Power BI Report Server does not support custom security."
