### ISSUE TITLE
A cookie associated with a cross-site resource  without the `SameSite` attribute

### ISSUE THREAD

**Issue by yls087412** [microsoft/Reporting-Services#196]
While access reports site in chrome 80, the console is warning：
A cookie associated with a cross-site resource at https://yourReportSite/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

How can I fixed it? Thanks!

**Comment by lsteffens** [comment]
The same happens with the most current update to the Edge browser based on Chromium.
As a workaround you can set the browser flag "SameSite by default cookies" to disabled - this works on both Chrome and Edge.

Not a perfect solution to tell every user to use this workaround or use Firefox instead...

I don't know if this can actually be fixed (other than Microsoft updates PBI) as the Power BI website uses .NET 4.7 - but the samesite attribute needs .NET 4.7.2 or 4.8 and newer to work. 

I'm also desperatly need a real sulution to this problem.

**Comment by yls087412** [comment]
> The same happens with the most current update to the Edge browser based on Chromium.
> As a workaround you can set the browser flag "SameSite by default cookies" to disabled - this works on both Chrome and Edge.
> 
> Not a perfect solution to tell every user to use this workaround or use Firefox instead...
> 
> I don't know if this can actually be fixed (other than Microsoft updates PBI) as the Power BI website uses .NET 4.0 - but the samesite attribute needs .NET 4.7.2 or 4.8 and newer to work.
> 
> I'm also desperatly need a real solution to this problem.

Thanks!!

**Comment by yls087412** [comment]
> The same happens with the most current update to the Edge browser based on Chromium.
> As a workaround you can set the browser flag "SameSite by default cookies" to disabled - this works on both Chrome and Edge.
> 
> Not a perfect solution to tell every user to use this workaround or use Firefox instead...
> 
> I don't know if this can actually be fixed (other than Microsoft updates PBI) as the Power BI website uses .NET 4.0 - but the samesite attribute needs .NET 4.7.2 or 4.8 and newer to work.
> 
> I'm also desperatly need a real solution to this problem.

Thanks a lot!!

**Comment by gboreki** [comment]
Which version of the product are you using? You can set these two properties in your web.config file:
https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.requiressl
https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.cookiesamesite

Let me know if you still have problems after doing this.

**Comment by lsteffens** [comment]
I did set:
<forms ... cookieSameSite="None" requireSSL="true"></forms>
and
<httpCookies sameSite="None" requireSSL="true" />

in the web.config of the reportserver ... and did the same for the portal site where I create the auth cookie.

Can you confirm that you actually see custom visuals in Power BI report server using custum authentication in your environment?
As this is the only visible problem seen by the enduser in Chrome or Edge (Chromium) ... (both browsers must be the most current versions)

**Comment by yls087412** [comment]
> Which version of the product are you using? You can set these two properties in your web.config file:
> https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.requiressl
> https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.cookiesamesite
> 
> Let me know if you still have problems after doing this.

Dear Gboreki, My PowerBi version is 1.8.7485.35104 (May 2020), I set the web.config like follow, but get the same warning.
--------------------------------------------------------------------------------------------------------------------------------------
 <authentication mode="Forms">
      <forms loginUrl="logon.aspx" name="sqlAuthCookie" timeout="60" path="/" cookieless="UseCookies" cookieSameSite="None" requireSSL="true">
      </forms>
    </authentication>

**Comment by yls087412** [comment]
> Which version of the product are you using? You can set these two properties in your web.config file:
> https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.requiressl
> https://docs.microsoft.com/en-us/dotnet/api/system.web.security.formsauthentication.cookiesamesite
> 
> Let me know if you still have problems after doing this.

Dear Gboreki, My PowerBi version is 1.8.7485.35104 (May 2020), I set the web.config like follow, but get the same warning.


<authentication mode="Forms">
      <forms loginUrl="logon.aspx" name="sqlAuthCookie" timeout="60" path="/" cookieless="UseCookies" cookieSameSite="None" requireSSL="true">
      </forms>
    </authentication>

**Comment by yls087412** [comment]
> I did set:
> `<forms ... cookieSameSite="None" requireSSL="true"></forms>`
> and
> `<httpCookies sameSite="None" requireSSL="true" />`
> 
> in the web.config of the reportserver ... and did the same for the portal site where I create the auth cookie.
> 
> Can you confirm that you actually see custom visuals in Power BI report server using custum authentication in your environment?
> As this is the only visible problem seen by the enduser in Chrome or Edge (Chromium) ... (both browsers must be the most current versions)
> 
> I'm using PBI Report Server Mai 2020 ...

hi lsteffens, I use powerbi May 2020, and set the custume authentication step by step as  https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample2016, and it works OK except get the cookieSameSite warning &  401 error.
GET https://mybisite/powerbi/libs/scripts/globalize.js net::ERR_ABORTED 401.

**Comment by lsteffens** [comment]
> hi lsteffens, I use powerbi May 2020, and set the custume authentication step by step as https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample2016, and it works OK except get the cookieSameSite warning & 401 error.
> GET https://mybisite/powerbi/libs/scripts/globalize.js net::ERR_ABORTED 401.

Hi yls087412. This is the behavior I see on my side ... but I get a bunch (~20) 401 errors including yours.

Are custom visuals (like Text Filter or Tag Cloud) visible for you? 
(using the most current Chrome or Edge (Chromium!) browser....)

Everything worked perfectly until Chrome and Edge updated their browsers to use "SameSite by default cookies" flag.
Firefox still works ok - but with warnings about the SameSite attribute.

**Comment by lsteffens** [comment]
The October 2020 release of Power BI works with Samesite default settings again.

It took some time, but this bug was fixed at last.

**Comment by yls087412** [comment]
> The October 2020 release of Power BI works with Samesite default settings again.
> 
> It took some time, but this bug was fixed at last.

It is a good news! thank you very much!
