### ISSUE TITLE
rsAccessDenied - Permissions insufficient to perform this operation (logon)

### ISSUE THREAD

**Issue by adrods** [microsoft/Reporting-Services#202]
Hello, I am implementing the security extension and I have the following problem. At the time of logon I get the error: The permissions granted to the user 'test' are insufficient to perform this operation. Test is a registered user and is in the database.
How can I give this user permissions if I can't enter the site?
Is there a generic user that has permissions?
With a windows user (who had permissions before implementing the security extension) should I log in?
Thank you!

**Comment by jtarquino** [comment]
In the sample [documentation](https://github.com/microsoft/Reporting-Services/tree/master/CustomSecuritySample) check the section "Locate the <Security> and <Authentication> elements, within the <Extensions> element, and modify the settings as follows:" , that entry defines what user will be an admin

**Comment by adrods** [comment]
Thanks, i can logon whit the admin user, but i hava a new problem, i see the page like this... 
![image](https://user-images.githubusercontent.com/73251773/96889288-d4858900-145c-11eb-8af8-f6f7ce9f7e29.png)

**Comment by jtarquino** [comment]
use /reports instead of /reportserver

**Comment by adrods** [comment]
i have the same problem... 
![image](https://user-images.githubusercontent.com/73251773/96891277-e36d3b00-145e-11eb-9d28-a21f7fbd4a29.png)



look this captures from the rs configuration manager.. i don't know if its ok, or the name "/reports" depends on this.
![image](https://user-images.githubusercontent.com/73251773/96891376-fb44bf00-145e-11eb-8adf-b5c7b9273056.png)

![image](https://user-images.githubusercontent.com/73251773/96891433-0ac40800-145f-11eb-8479-bcd3a2e4096b.png)

**Comment by jtarquino** [comment]
its the one from the Web Portal Url
