### ISSUE TITLE
RLS settings have been deleted from server without any user manipulations

### ISSUE THREAD

**Issue by sanederchik** [microsoft/Reporting-Services#213]
Platform: `Power BI Report Server`

For some reasons, I can't log in `community.powerbi.com`, so I write a question here.

Today all RLS roles assignments have been removed from server itself, without any user actions.
Just to illustrate this issue, there were hundreds of role assignments before this strange error.

![image](https://user-images.githubusercontent.com/30187683/103219623-4aabdd80-492f-11eb-91a2-96ed4523f5ce.png)

As you can see in an above-added snapshot, now there are only few of them, which I had to add manually after this crash.

**Is it possible to restore values of `Row-level security` tab which were active yesterday, for example?**

**Comment by gboreki** [comment]
Hello Sanederchik,

Roles would be removed either through an user action, api call or report being overwritten without the same roles (which would cause the roles themselves to be removed). I suggest to check the server log files for the specific ItemId to confirm there were indeed no actions. 

There is no history for catalog items in Power Bi Report Server, so recovering to a previous state is only possible by recovering a backup of your report server catalog at the previous state (keep in mind that this would recover the state of all items, there is no out of box mechanism for partial recovery).

Thanks
-G
