### ISSUE TITLE
Login in mobile power bi app

### ISSUE THREAD

**Issue by adrods** [microsoft/Reporting-Services#214]
Hi, I have a question about how this login would work with the mobile application. 
When I login to the mobile application, are the same checks carried out as I have in the custom login? 
Could I login with the users that I have saved in the database?

Thanks!

**Comment by gboreki** [comment]
The powerbi mobile application does not support custom authentication. I suggest to post (or vote on an existing) idea under ideas.powerbi.com so this can be considered for a future release.
