### ISSUE TITLE
CustomSecuritySample TooMany Redirect Issue after version of Chrome 80+

### ISSUE THREAD

**Issue by saltiner** [microsoft/Reporting-Services#219]
Hello, we deployed CustomSecuritySample in our environment and everyting was fine before upgrade our customers chrome versiyon to 86. when we investigated the issue we learned that chrome disabled samesite options. if we change "SameSite by default cookies" flags to Disabled then everything works. but we don't want to use this one because of our security teams. is there any other option that we can pass the issue?

**Comment by gboreki** [comment]
What is the version and build of SSRS you are using? In newer versions you can install .net framework 4.72+ and set the property as part of web.config, for example:
   <authentication mode="Forms">
      <forms loginUrl="logon.aspx" name="sqlAuthCookie" timeout="60" path="/" **### cookieSameSite="None" requireSSL="True"**>
      </forms>
    </authentication>

You can read and choose the appropriate value for your server at:
https://docs.microsoft.com/en-us/aspnet/samesite/system-web-samesite

**Comment by Et3rnal** [comment]
I'm having this issue, I have changed the target to 4.7.2 and 4.8 and added the changes to the `web.config` but still not getting the SameSite with the set-Cookie header, no errors
No idea what else to try

@gboreki Can you help, please
