### ISSUE TITLE
Power BI RS. Fields with datatype 'time' recalculated to GMT+0

### ISSUE THREAD

**Issue by sanederchik** [microsoft/Reporting-Services#220]
After the latest update of `Power BI Report Server` to October 2020 we faced a problem with several reports. This problem is that a `Portal` version of `Power BI RS` recalculated all `time` values to `GMT+0` format. For example, if I had a value `09:00` in a table cell, I would see `06:00` instead. Simultaneously, in `Power BI RS Desktop` and in `dataset` I have a correct value of `09:00`. Moreover, if I refresh manually at my PC and load a report manually into `Power BI RS Portal`, I would see correct time of `09:00` until the next automatic report refresh.

You can't imagine how it irritates users right now. I kindly ask you to make an update of `Power BI RS Portal` version as soon as possible in order to solve this problem.

**Comment by gboreki** [comment]
Hi Sanederchik,

I haven't heard of this issue before, given that its not a problem with the samples from this repo, I suggest that you get in touch directly with Microsoft support so our support team can work with you in getting a repro and have an official channel to provide updates.

Thanks
-G
