### ISSUE TITLE
After the CustomSecuritySample runs successfully, the mobile app cannot connect to the Powerbi report server

### ISSUE THREAD

**Issue by luckyClover233** [Microsoft/Reporting-Services#261]
Thank you for CustomSecuritySample provided. 

I successfully ran it according to readme. The computer can log in to the report server normally.
However, I found that I cannot connect to the server on the mobile app.
Prompt: Please verify the report server address.
Before running, my mobile app successfully connected to the Powerbi report server.

After running, how do I connect to the report server through the mobile app?

**Comment by gboreki** [comment]
The powerbi mobile app unfortunaly does not support custom authentication.

**Comment by luckyClover233** [comment]
so sad

**Comment by luckyClover233** [comment]
thank you all the same
