### ISSUE TITLE
Not redirect long inactive user to logon.aspx 

### ISSUE THREAD

**Issue by astashkevich39** [Microsoft/Reporting-Services#27]
Hello. 
If the user is inactive for longer than specified in the parameter <Forms timeout >and then try click on the report of folder it does not redirect to logon.aspx. Portal try load logon.aspx with XMLHTTPRequest into current page.

**Comment by gboreki** [comment]
This issue was a defect in the serverin how it handled expired cookies, and was fixed in SSRS2016, 2017 and Power BI RS
