### ISSUE TITLE
Does this extension work with Power BI Desktop (June 2017) Optimized for PBIRS?

### ISSUE THREAD

**Issue by tplatt37** [Microsoft/Reporting-Services#29]
Are these custom auth extensions compatible with Power BI Desktop?  I had setup a PBIRS server, using IWA auth, confirmed it was working with Power BI Desktop , but after applying the security extensions (which work fine from the web portal), the desktop program no longer recognizes the PBIRS server as being valid.  The error message is "We couldn't find a Power BI Report Server at that address". This is from the Power BI Report Server options under "File", "Open" or "File", "Save As".  I am using the Power BI Desktop program released June 2017.

I realize this question may be out of scope for this project, but just wondering if anyone has encountered similar.

**Comment by jtarquino** [comment]
Power BI Desktop doesn't support the custom authentication extensions yet, however you still can use the portal to upload the Power BI Desktop files to the portal and render them in the server.

If you would like to have this feature, please vote and comment on https://ideas.powerbi.com/forums/265200-power-bi-ideas/category/207604-report-server

Thanks

**Comment by tplatt37** [comment]
Thank you for the prompt response.
