### ISSUE TITLE
Only the built-in admin account or username-specific ACLs work to show the "Manage" option

### ISSUE THREAD

**Issue by rmariotti-choicelunch** [Microsoft/Reporting-Services#31]
I wanted first to THANK those that created and maintain this very helpful codebase.  I have a working SSRS 2016 instance using the code, modified to point to my own custom user store database.  I started with a clean ReportServer database with only the needed elements to test my feature.

I have also written a simple way to manage GROUPS so that I don't have to manage individual people in the SSRS ACLs but instead can assign permissions to "Accounting".  My custom DB returns a list of groups matching the principalUser and then compares that to the ACL list.  All good.  My group settings are correctly controlling the folders and access.  

However, **I cannot see the "Manage" options on either a Folder or a report (clicking the "..." to show the popup of options) using the group setting.**  This ONLY works under the following conditions:
• I'm logged in as the special admin user who bypasses the CheckAccess() methods
• I have an ACL that specifies the exact username (vs. the group name e.g. "Accounting")

When comparing the activity for an ACL set with a specific username vs an ACL set with a group, I see that, when clicking the "..." on a report, CheckAccess() is called the same # of times and they both return true.  And neither of them return false for any of the CheckAccess().  But only the use case where the ACL includes the exact username does it show the Manage options.

**Is it possible that this project is omitting one of the signatures for CheckAccess() that is used to show the "Manage" option?**  I see 10 CheckAccess(), which matches the IAuthorizationExtension, so maybe not.  

Any thoughts?  Has anyone implemented group-based custom auth?

**Comment by rmariotti-choicelunch** [comment]
Found my issue: I needed to also implement my custom group/role in the GetPermissions() method (not just in the various CheckAccess() methods).  Working.

**Comment by adopilot** [comment]
@rmariotti-choicelunch 

> I have also written a simple way to manage GROUPS so that I don't have to manage individual people
Can you please describe a little who you managed to get groups working with custom extension on SSRS. 
I am trying also to manage permissions  on SSRS for groups of user.
But I can't push SSRS to Rolle assing to group or to set premisions for group.
Did you open your groups through windows , ad ,api or injecting in SQL?
Or you define group as user in SSRS and then in login method beside user name returning group name ?

**Comment by rmariotti-choicelunch** [comment]
@adopilot in my case, I added code to query a custom database for group membership (inside the CheckAccess() and GetPermissions() methods that are part of the CustomSecurity SSRS sample.  

Like this: 

`	  public bool CheckAccess(
		string userName,
		IntPtr userToken,
		byte[] secDesc,
		ModelItemOperation modelItemOperation)
	  {
      // If the user is the administrator, allow unrestricted access.
      // Because SQL Server defaults to case-insensitive, we have to
      // perform a case insensitive comparison. Ideally you would check
      // the SQL Server instance CaseSensitivity property before making
      // a case-insensitive comparison.
      if (0 == String.Compare(userName, m_adminUserName, true,
            CultureInfo.CurrentCulture))
        return true;

            AceCollection acl = DeserializeAcl(secDesc);
            foreach (AceStruct ace in acl)
            {
                if (0 == String.Compare(userName, ace.PrincipalName, true, CultureInfo.CurrentCulture))
                {
                    foreach (ModelItemOperation aclOperation in ace.ModelItemOperations)
                    {
                        if (aclOperation == modelItemOperation)
                            return true;
                    }
                }
                else
                {
                    // check to see if this users' GROUP membership has access
                    DataTable dt = GetGroupMembership(userName);
                    foreach (DataRow role in dt.Rows)
                    {
                        string rolename = (string)role["RoleName"];
                        if (0 == String.Compare(rolename, ace.PrincipalName, true, CultureInfo.CurrentCulture))
                        {
                            foreach (ModelItemOperation aclOperation in ace.ModelItemOperations)
                            {
                                if (aclOperation == modelItemOperation)
                                    return true;
                            }
                        }
                    }
                }
            }

            return false;
	  }`
