### ISSUE TITLE
Error while building the solution

### ISSUE THREAD

**Issue by rachidadukes** [Microsoft/Reporting-Services#32]
I followed all the steps until this section from this link, but I tried to build the solution following the step **Step 2: Building the Sample**
I run into two errors:

Error	CS0246	The type or namespace name 'IAuthenticationExtension2' could not be found (are you missing a using directive or an assembly reference?)	CustomSecurity	C:\TEMP\CustomSecuritySample2016\AuthenticationExtension.cs	35	Active

Error	CS0246	The type or namespace name 'IRSRequestContext' could not be found (are you missing a using directive or an assembly reference?)	CustomSecurity	C:\TEMP\CustomSecuritySample2016\AuthenticationExtension.cs	112	Active

Can you help?
Thanks,
Rachida
![2017-08-02_8-21-12](https://user-images.githubusercontent.com/8819903/28875292-0d1b30b6-7763-11e7-867c-784ee16355a8.gif)

**Comment by jtarquino** [comment]
Did you add the reference to Microsoft.ReportingServices.Interfaces ?

**Comment by rachidadukes** [comment]
Thanks Jaime for your fast response. I just found out that I was referencing to the file  Microsoft.ReportingServices.Interfaces which is located in C:\Program Files\Microsoft SQL Server\MSRS12.MSSQLSERVER\Reporting Services\ReportServer\bin
Which means that it was referencing to the dll of SQL Server 2014 instead of 2016.
Thanks,
Rachida
