### ISSUE TITLE
SSRS 2106 Custom authentication extension - sqlAuthCookie issue

### ISSUE THREAD

**Issue by gladsonwilliam** [Microsoft/Reporting-Services#36]
HELLO :

We are following the instructions to implement a custom authentication provider for ssrs 2016 from the ssrs 2016 online doc and the sample application works fine.

https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample 

We have a created a ASP.NET HttpHandler and deployed in IIS and we are using the ReportService2010.asmx reporting service. We are doing this because we are injecting some custom JavaScript and css to meet some business requirements. 

In the handlers ProcessRequest method we are making a Web request to the URL “http://xxxx/ ReportServer/logon.aspx?ReturnUrl=http://xxxx/Reports” and the custom login page is displayed.

In the custom Logon.aspx.cs under “ServerBtnLogon_Click”  event we are not calling the FormsAutherntication.RedirectFromLoginPage method rather simply returning back to the handler, this response contains the “sqlAuthCookie”

After getting the response we are creating a new request and adding this “sqlAuthCookie” into the request object  and making a new web request to this url “http://xxxx/Reports/browse”. The domain name doesn't contain any underscore. 

We are getting the following error “e ERROR: [3je9vl7o]: XSRF Failed (NonceCookieNotFound)”.

Any help in this regard is really appreciated.

**Comment by mm4707** [comment]
Did you try
https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample2016  ??
It's different 
https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample

If your ssrs is 2016 version
you have to try CustomSecuritySample2016

**Comment by vpratti** [comment]
@gladsonwilliam Can you please share your handler code and also the code in the login.aspx.cs where you are returning the sqlauthcookie. I am running into  similar situation. Thank you
