### ISSUE TITLE
How use ReportingService2010 to get list report

### ISSUE THREAD

**Issue by tuananhti** [Microsoft/Reporting-Services#40]
Hello, 

- I create other project and reference server to ReportService2010.asmx

- How i pass username and password (auth by forms) to get list report

**Comment by parthsha** [comment]
@tuananhti did you set up Forms Authentication on your instance on Reporting Services?

**Comment by jtarquino** [comment]
Take a look at the LogonUser method
https://docs.microsoft.com/en-us/sql/reporting-services/extensions/security-extension/authentication-in-reporting-services
