### ISSUE TITLE
Instructions for adding MachineKey conflict with gen tool regarding casing

### ISSUE THREAD

**Issue by brentminder** [Microsoft/Reporting-Services#41]
Here are the instructions for creating a machine key (as of 2017-08-31). The generator link produces lowercased attributes which are warned against in the text "Check the casing of the attributes, it should be Pascal Casing...."

> Step 4: Generate Machine Keys
> 
> Using Forms authentication requires that all report server processes can access the authentication cookie. This involves configuring a machine key and decryption algorithm - a familiar step for those who had previously setup SSRS to work in scale-out environments.
> 
> Generate and add <MachineKey> under <Configuration> in your RSReportServer.config file.
> 
> <MachineKey ValidationKey="[YOUR KEY]" DecryptionKey="[YOUR KEY]" Validation="AES" Decryption="AES" />
> Check the casing of the attributes, it should be Pascal Casing as the example above
> 
> There is not need for a <system.web> entry
> 
> You should use a validation key specific for you deployment, there are several tools to generate the keys such as Internet Information Services Manager (IIS) and http://www.a2zmenu.com/utility/machine-key-generator.aspx.

**Comment by jtarquino** [comment]
The generator is just a reference, I have updated the documentation to use a powershell script that you can customize

**Comment by brentminder** [comment]
Hi Jaime,

Thanks for updating the doco.

Do you know if SSRS 2016 supports non-paginated reports using Custom Auth &
Security?

Thanks,

Brent

**Comment by jtarquino** [comment]
It does in the browser

**Comment by brentminder** [comment]
Great. Thanks!
