### ISSUE TITLE
2016 Mobile Reports and Power BI Reporting Server Authentication

### ISSUE THREAD

**Issue by GeoffBallard** [Microsoft/Reporting-Services#42]
Does this custom Auth provider work when running 2016 Mobile Reports and Power BI reports on Power BI Reporting Server (is it just for Paginated Reports)

**Comment by jtarquino** [comment]
It works for all the report types in the browser

**Comment by gregoriogreen** [comment]
Hi Guys - I have been trying to set up this configuration and so far getting a configuration error. I did a PowerBI ReportServer repair (works great!) and plan to make a new attempt today.
