### ISSUE TITLE
After set up, a new user gets RsAccessDenied - what am I missing?

### ISSUE THREAD

**Issue by gregoriogreen** [Microsoft/Reporting-Services#43]
Hi - I set up SRS FormsAuth on 2016 Enterprise and followed all instruction. When a new user registers by clicking RegisterUser that user is visible in the [UserAccounts].[dbo].[Users] table. So database connection is working. But then if the user attempts to log in they receive RsAccessDenied - this shows in the ReportServer\log files.

So I set up Power BI ReportServer. This produced the same result. I was clever enough to update the paths to Reflect install location or PowerBI ReportServer.

I've spent a lot of time on this. Same results or total breakage each time. I suspected a role issue, but once the reportserver is in FormsAuthentication mode I can't create roles as I can't connect. In SQL Management Studio 17.2 I was once able to connect to the ReportServer using the user I registered but that user had no privileges.

What am I missing? Thank in advance.

**Comment by peteratkinson** [comment]
We managed to get this working, but ran into a similar issue. Would be helpful to hear from others that had a working solution.

**Comment by jtarquino** [comment]
@gregoriogreen in the config file you define an administrator that will have all the permissions and can give permissions to the other users , that administrator is called  in the sample**username** , you should replace it with the name of the user you want as an admin
```xml
<Security>
	<Extension Name="Forms" Type="Microsoft.Samples.ReportingServices.CustomSecurity.Authorization, Microsoft.Samples.ReportingServices.CustomSecurity" >
	<Configuration>
		<AdminConfiguration>
			<UserName>username</UserName>
		</AdminConfiguration>
	</Configuration>
	</Extension>
</Security>
```
