### ISSUE TITLE
OWIN cookie

### ISSUE THREAD

**Issue by duncanmhor** [Microsoft/Reporting-Services#47]
Hi,
I've used this sample successfully in the past when consuming a forms authentication cookie. I'm trying to do the same thing, but consume a cookie that is generated by an app using OWIN middleware. I've tried to add an OWIN startup class but the code is never called. Do you know if what I'm trying to achieve is possible?

**Comment by jtarquino** [comment]
You can't inject OWIN pipelines into the Reporting Services Portal

**Comment by duncanmhor** [comment]
Oh well, plan B then. Thanks
