### ISSUE TITLE
SQL Connect issue

### ISSUE THREAD

**Issue by gregoriogreen** [Microsoft/Reporting-Services#48]
Every attempt to register a user gets this error:

**An error occurred while attempting to add the account. Request for the permission of type 'System.Data.SqlClient.SqlClientPermission, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.**

I've tried many configurations. Also downloaded the project afresh and started over. Also changed the connection string in the sample application to use a specific SQL user account which has necessary permissions. And every time the login page returns the above. Also added specific user and PowerBiReportServer account to the table and stored procedure. Also successfully set up on Server 2012 machine. This server is Server 2016 and same settings don't seem to produce same result.

StackOverflow users suggest changing the trust settings of the application but as this is a class library application it doesn't have those settings at least not in the usual location.

Any suggestions? Thanks in advance.

**Comment by jtarquino** [comment]
Validate you have updated the RSSrvPolicy.config file

**Comment by gregoriogreen** [comment]
Yes I did, still getting same result.

**Comment by jtarquino** [comment]
Please also check the URL is accurate regarding the folder for PBIRS which is different than SSRS, I just updated the documentation with the right folder for PBIRS https://github.com/Microsoft/Reporting-Services/blob/master/CustomSecuritySample/README.md#step-3-deployment-and-configuration

**Comment by gregoriogreen** [comment]
I was able to resolve this. The root cause of the issue was a misinterpretation of the instructions. As I am running SQL2016 I tried to use the CustomSample2016 while following the ReportServer PBI instructions wherever I could find them (in CustomSample).

It might be helpful to have three versions of instruction

- SRS Prior to SQL2016
- SRS 2016
- PBI [version] which deserves a stand-alone sample and instruction.

Thank you, this is great software. Looking forward to the OAuth2 Azure AD / Office 365 Auth Sample.

**Comment by martinmedia-github** [comment]
> I was able to resolve this. The root cause of the issue was a misinterpretation of the instructions. As I am running SQL2016 I tried to use the CustomSample2016 while following the ReportServer PBI instructions wherever I could find them (in CustomSample).
> 
> It might be helpful to have three versions of instruction
> 
> * SRS Prior to SQL2016
> * SRS 2016
> * PBI [version] which deserves a stand-alone sample and instruction.
> 
> Thank you, this is great software. Looking forward to the OAuth2 Azure AD / Office 365 Auth Sample.

-- So you managed to resolve this... but what did you do to resolve this ? I have the same issue and I followed the instructions on the 2016 sample: https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample2016
