### ISSUE TITLE
tool bar, and undesired area

### ISSUE THREAD

**Issue by MichaelEvanchik** [Microsoft/Reporting-Services#5]
I am on the latest preview 10/4/2016, installed in my project Visual Studio 2015, I have NuGet the latest preview and installed into the GAC of SQL Server 2016(backing up the older files first as this is a preview)

I also previous to all of this installed SQL2016 cumulative update 2

chrome gives me this error

/Reserved.ReportViewerWebControl.axd?OpType=BackImag…1.5&Color=%23ECE9D8&Name=Microsoft.Reporting.WebForms.Icons.toolbar_bk.png Failed to load resource: the server responded with a status of 404 (Not Found)

Also i get an undesired area

[http://i.stack.imgur.com/7aG0D.png](http://i.stack.imgur.com/7aG0D.png)

This is my only issue left is this undesired area.  Here is my code.

'<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="DKNYWeb.Default" %>

'<%@ Register assembly="Microsoft.ReportViewer.WebForms, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" namespace="Microsoft.Reporting.WebForms" tagprefix="rsweb" %>

        '<!DOCTYPE html>

         html xmlns="http://www.w3.org/1999/xhtml"
         head runat="server"
          meta http-equiv="X-UA-Compatible" content="IE=edge" 
          title title
          /head
          body
           form id="form2" runat="server"
            asp:ScriptManager ID="ScriptManager1" runat="server"

            asp:ScriptManager
                     rsweb:ReportViewer ID="ReportViewer1" runat="server" ProcessingMode="Remote" Width="100%" 
                    ServerReport ReportPath="/Reports_2016Prod/DatacaptureReport_DKO_Revised_V2" ReportServerUrl="http://sql2016a.intranet.com/ReportServer_SQL2016" /
                    /rsweb:ReportViewer
             form
            body
            html'

the web.config is verbatim on this site.  I also have the most updated AjaxControlTookit possible

**Comment by RhysSchmidtke** [comment]
Hi Michael, earlier version of SQL Server Data Tools incorrect GAC'ed certain dlls that conflict with the Report Viewer Control - seems this might be what's causing this issue. Try updating SSDT to the latest version, or remove the 13.0.0.0 version of the Microsoft.ReportViewer assemblies from the GAC

Check out https://github.com/Microsoft/Reporting-Services/blob/master/Docs/Get-Started-With-RVC.md#next-steps---read for more info.

**Comment by RhysSchmidtke** [comment]
Also, you don't need to GAC the new versions of the Report Viewer Control libraries - just including in your project via nuget.

**Comment by MichaelEvanchik** [comment]
i found the issue, although my development machine had the latest SSDT, and my SQL Server VM(which has 2012 and 2016 on it) as the latest SSDT, the issue was immediately resolved when i installed the latest SSDT on my IIS8 VM machine.   I would assume the iis web app would use the /bin directory dlls but the GAC overwrides this?

**Comment by jtarquino** [comment]
Gac  always wins

**Comment by MichaelEvanchik** [comment]
either way it wasnt until september (using preview dll's) that this report viewer even works

**Comment by RhysSchmidtke** [comment]
:) The latest SSDT update should resolve the issue, with the next update of the ReportViewerControl the team is going to bump the dll versions which will also fix the issue for people who have the old libraries gac'ed.

**Comment by MichaelEvanchik** [comment]
i wish i could fix this issue as well, [http://stackoverflow.com/questions/39757833/asp-net-webforms-site-using-ssrs-2012-reportviewer-loading-disappears-and-times](http://stackoverflow.com/questions/39757833/asp-net-webforms-site-using-ssrs-2012-reportviewer-loading-disappears-and-times)
