### ISSUE TITLE
IIS Redirect and URL rewrite to this SRS possible - from SSL site?

### ISSUE THREAD

**Issue by gregoriogreen** [Microsoft/Reporting-Services#51]
I've tried unsuccessfully to implement an IIS "front-end" site to SRS when in forms auth mode. The goal is to have a site which authenticates using Oauth2 (Azure AD) and then hands the authenticated user through to this sample. Two layers of security. 

So I installed URL Rewrite 2.1 and HTTP Redirect. No combination of their features with SRS seems to accomplish the goal.

I want traffic to continue to route through to SRS on another IP address. I have SSL Offloading enabled, and also have tried without. Each time the session gets handed off from IIS the best I can do is get the user to SRS on an internal IP - but not on a public IP with SSL.

Happy to explain further if this is not clear. Is there something inherent to SRS (maybe that it's not an IIS site) which will forever prevent my objective?

Thanks in advance.

**Comment by jtarquino** [comment]
As far you are authenticated to SSRS it should work, you need to ensure that what you are implementing is able to authenticate to SSRS
