### ISSUE TITLE
Add image to login page from URL (without SSL warning)?

### ISSUE THREAD

**Issue by gregoriogreen** [Microsoft/Reporting-Services#52]
I modified the login page to make it pretty with a background image via URL. I tried placing my background image in ReportServer folder(s) but no relative path seems to get it picked up.  So I had to serve this image from IIS on same domain, but the non-SSL port 80 site as the port 443 SSL is bound to ReportServer_PBI . Regardless of where I put the image, the user receives an "insecure" warning because the image is not coming from the SSL port 443 PBI SRS site.

Is there an URL that will do that on the SRS PBI?

Thank you,

**Comment by omankit** [comment]
Don't do this. It's wrong way. place image on ssl site.

**Comment by jtarquino** [comment]
Other option is to embed the image as base64 in your html page
