### ISSUE TITLE
In CustomSecuritySample2016

### ISSUE THREAD

**Issue by mm4707** [Microsoft/Reporting-Services#53]
In CustomSecuritySample2016
Step 3.
If I followed this 
![default](https://user-images.githubusercontent.com/27001532/31422058-505d9346-ae86-11e7-8155-feceb63edd07.JPG)

I can only use one user
And How can I dynamic UserName ??
And How can I more UserName ??

**Comment by jtarquino** [comment]
You can only specify one user there which is the administrator, after that you can use the login page to add more users, and then in the portal add permissions for those new added users
