### ISSUE TITLE
How to build if SSRS is not in the default location?

### ISSUE THREAD

**Issue by imtiazu** [Microsoft/Reporting-Services#55]
Hi there, working my way through the setup (i'm not a coder) and my SSRS install isn't in the default install location as I installed it after installing SQL server. How can I change the default location in the solution to this location? Thanks.

**Comment by jtarquino** [comment]
You can use the new folder from visual studio
Click Browse, and find Microsoft.ReportingServices.Interfaces on your local drive. By default, the assembly is in the <install>\ReportServer\bin directory. Click OK. The selected reference is added to your project.
