### ISSUE TITLE
Custom authentication extension issue

### ISSUE THREAD

**Issue by arekku** [Microsoft/Reporting-Services#56]
I seem to be having an issue with my custom extension after following the sample. The issue is that I can log into the report server but get an error 500: unable to validate data, when I try and view the portal (localhost/reports). I have include my config files in case i made a mistake within.

[Logs and configs.zip](https://github.com/Microsoft/Reporting-Services/files/1458266/Logs.and.configs.zip)

**Comment by arekku** [comment]
This was because of the hosting service failing to copy the key from RSReportServer to Web.Config. Default service user must have write permission to web.Config. Please correct me if im wrong.

**Comment by jtarquino** [comment]
Yes it needs to copy the key into the web.config
