### ISSUE TITLE
Nuget package library for interaction with SSRS Rest API not available

### ISSUE THREAD

**Issue by xantari** [Microsoft/Reporting-Services#60]
Please provide a nuget package for easy install SSRS Rest API interactions.

Right now the only option is Swagger.

But when using Swagger, how to keep library updated as Microsoft improves the swagger library?

In nuget you get package update notifications?

This requires setting up a whole big .NET project and compiling in our 100 applications by adding reference to that project.

Would be easier if just in package.config and it automatically restores on checkout.

**Comment by jtarquino** [comment]
I would like to invite you to add the idea to our User Voice program https://ideas.powerbi.com/forums/265200-power-bi-ideas?category_id=207604

**Comment by xantari** [comment]
Put this feature request in: https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/40742506-provide-a-nuget-for-power-bi-report-server-rest-ap
