### ISSUE TITLE
Custom security extension and subscriptions

### ISSUE THREAD

**Issue by YvesR** [Microsoft/Reporting-Services#61]
Using a custom security extension against another user database it is necessary to store connection to this target database in the web.config file to make it work.

In the old security extension for SQL 2008-2014 it is necessary to also to set this data if you want to use subscriptions.

I posted details once here: [Error subscription delivery in SSRS with custom security extension](https://stackoverflow.com/questions/19271651/error-subscription-delivery-in-ssrs-with-custom-security-extension)

So, is this still necessary using this new extension, here?

**Comment by jtarquino** [comment]
We have not made changes in that area.
You can propose the improvement in ideas.powerbi.com
