### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by JatinKinra** [Microsoft/Reporting-Services#62]
Hi, I followed all the steps mentioned in the README.
Finally, when I re-run the SSRS server, I get this error -
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
http://localhost/ReportServer/Logon.aspx?ReturnUrl=/ReportServer/localredirect?url=%252fReports

Am I missing something here ?

**Comment by jtarquino** [comment]
Can you check the logs to see what is the error.
Also double check you are using validation Sha1 when generating the keys, or use IIS to generate the keys

**Comment by JatinKinra** [comment]
Hey @jtarquino. Thanks for replying. I was using AES validation when generating keys, as mentioned here https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample2016.
But, I also tried using Sha1, but same issue persists.

**Comment by jtarquino** [comment]
I have heard some issues generating the keys with that article, please use IIS instead, also can you check the logs and share the error

**Comment by ganeshmahajan1985** [comment]
Hi @JatinKinra what's the solution ? did you find anything ?
can you please help to me? I am also stuck on this.
