### ISSUE TITLE
Unable to connect to SQL Server

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services#65]
When i click register user got below error:

An error occurred while attempting to add the account. A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) SQL Server Reporting Services Sample 

Changed in App.Config; build and copied latest dll and pdb files
Named pipes is enabled;
Server Name: xyz\sql2016

<value>Server=xyz\SQL2016; Integrated Security=SSPI;database=UserAccounts</value>

Its on same Server.

**Comment by jtarquino** [comment]
Verify you can connect to the SQL server Database using the service account (as you have integrated security in your connection string)

**Comment by sneevand** [comment]
everything is installed on Laptop; we are testing it locally before we can deploy to server and end up with that error.

**Comment by jtarquino** [comment]
Database is specified in the app.config [Line 15](https://github.com/Microsoft/Reporting-Services/blob/e35ad603870631aeba26f78f62e71e424db0a70c/CustomSecuritySample/app.config#L15)

**Comment by sneevand** [comment]
i know that and i changed it but how does the SSRS logon page identify that when we deploy only dll and pdb file?

**Comment by jtarquino** [comment]
You need to copy also the app.config

**Comment by sneevand** [comment]
Can you update the document please; so that it will be followed accordingly and no further issues are raised on it.

**Comment by sneevand** [comment]
issue was that my server has instance name;  i chnaged it to full qualified name with port number; works fine.
