### ISSUE TITLE
Getting Error while trying to consume Reporting Service and getting list of Reports

### ISSUE THREAD

**Issue by sameersayani** [Microsoft/Reporting-Services#66]
Hi Tarquino,
I encountered a issue while I am trying to get list of all reports by creating object of Reporting Service proxy class. I had successfully implemented Custom Authentication. When I login from Browser, I can run all reports there but my requirement is to show a Treeview with all Reports Name (URL). When someone clicks of it, it will open the report in new tab. If I do so using Windows Authentication, everything works fine but when trying same with Custom/Forms Authentication I am getting error as attached below.
![img_pwynzd](https://user-images.githubusercontent.com/4317847/36675880-32933aac-1b30-11e8-9afa-cddafbdd545d.jpg)

**In my Logon.aspx page, If I write userIdentity = new GenericIdentity(WindowsIdentity.GetCurrent().Name); then it gives error User "" don't have permissions to view this. If I comment it, then It gives attached error. Can you shed some light on this?**

Thanks,
Sameer

 _public void GetUserInfo(out IIdentity userIdentity, out IntPtr userId)
       {
           // If the current user identity is not null,
           // set the userIdentity parameter to that of the current user 
           if (HttpContext.Current != null
                 && HttpContext.Current.User != null)
           {
               userIdentity = HttpContext.Current.User.Identity;
           }
           else
           // The current user identity is null. This happens when the user attempts an anonymous logon.
           // Although it is ok to return userIdentity as a null reference, it is best to throw an appropriate
           // exception for debugging purposes.
           // To configure for anonymous logon, return a Gener
           {
                //default the userIdentity
                userIdentity = new GenericIdentity(WindowsIdentity.GetCurrent().Name);
                //System.Diagnostics.Debug.Assert(false, "Warning: userIdentity is null! Modify your code if you wish to support anonymous logon.");
                // throw new NullReferenceException("Anonymous logon is not configured. userIdentity should not be null!");
            }

           // initialize a pointer to the current user id to zero
           userId = IntPtr.Zero;
       }_

**Comment by jtarquino** [comment]
Are you passing the credentials when you are creating the proxy?
@gboreki any other comment

**Comment by sameersayani** [comment]
Yes I am. Here's my code:-
rs = new RSWS2010Demo.ReportingService2010();
                //// Create an instance of the Web service proxy and set the credentials
                //rs.Credentials = System.Net.CredentialCache.DefaultCredentials;
                NetworkCredential nwc = new NetworkCredential(ConfigurationSettings.AppSettings["username"], ConfigurationSettings.AppSettings["password"], ConfigurationSettings.AppSettings["domain"]);
                rs.Credentials = nwc;
                //rs.Credentials = System.Net.CredentialCache.DefaultCredentials;
                rs.Url = ConfigurationSettings.AppSettings["RSWS2010Demo"];
               
Problem comes at this line : rs.ListChildren("/", false);

**Comment by jtarquino** [comment]
You need to use the method [LogonUser ]((https://msdn.microsoft.com/library/reportservice2010.reportingservice2010.logonuser(v=SQL.130).aspx))

**Comment by sameersayani** [comment]
OK I used LogonUser method, commented out other code. Now getting below error:-
**The permissions granted to user '' are insufficient for performing this operation. ---> Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: The permissions granted to user '' are insufficient for performing this operation.**

**Comment by sameersayani** [comment]
After using LogonUser method, here is the error I am getting  **The permissions granted to user '' are insufficient for performing this operation. ---> Microsoft.ReportingServices.Diagnostics.Utilities.AccessDeniedException: The permissions granted to user '' are insufficient for performing this operation.** Can you shed some light on this Tarquino !

**Comment by gboreki** [comment]
You need to ensure the user does have permissions to read items from the root. In the sample, the user that you put as part of the <Configuration> node for the authorization extension will have all permissions. You have to login that user first (using the portal) and then give permissions to any other users.

Second, you need to allow cookies in your ReportService2010 object:
`rs.CookieContainer = new CookieContainer();`

This will allow the authentication cookie that resuls from LogonUser to be used by other calls.
