### ISSUE TITLE
SSRS API in C# not working

### ISSUE THREAD

**Issue by rajurh** [Microsoft/Reporting-Services#67]
I have been trying to access the list of items available in folder using SSRS API provided in the below link
https://app.swaggerhub.com/apis/microsoft-rs/SSRS/2.0#/CatalogItems/GetCatalogItemContent

It works in Postman using NTLM Authentication but if i use the restsharp generated code in application it's says bad request. Below is the sample code snippet.

var client = new RestClient("https://xyz.com/Reports/api/v2.0/Folders");
var request = new RestRequest(Method.GET);
request.AddHeader("Postman-Token", "34c264d7-c5dd-4627-83c3-3ab0c9bd34d6");
request.AddHeader("Cache-Control", "no-cache");
request.AddHeader("Authorization", "NTLM TlRMTVasdsdasdAAAGAAYAIoAAAAYABgAogAAAAAAAABIAAAAQgBCAEgAAAAAAAAAigAAAAAAAAC6AAAABYKIogUBKAoAAAAPYQBuAHUALgBuAGEAdABhAHIAYQBqAGEAbgBAAG0AYQBuAGQAcwBjAG8AbgBzAHUAbAB0AGkAbgBnAC4AYwBvAG0AjNGwxwPlD50AAAAAAAAAAAAAAAAAAAAACK3AYrd3VdOkQQxatGwQi2u3HRk6kexp");
IRestResponse response = client.Execute(request);

**Comment by jtarquino** [comment]
Check in the report server logs what is the error your client is generating, that would give you a better idea of the issue 
@edugonz any other pointer?

**Comment by rajurh** [comment]
Nothing found in logs. Interesting part is thing which works in postman same is not working in c#. There is no error in executing or calling API code mentioned above it says in response status code has "Bad request" and content length is coming Zero. 

In the github there is a sample for JS,HTML 5 and Powershell can you please post a sample for C# please?

**Comment by rajurh** [comment]
I found the issue thought Restclient says pass in header through post man but in c# when you make request you should pass using Request credentials not through header.

**Comment by sumeshpu484** [comment]
@rajurh i am trying to get data from a report.can you pls tell me howto get data from a report plss....
