### ISSUE TITLE
Not able to upload rdl or create DS

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services#69]
![1](https://user-images.githubusercontent.com/13268402/36815579-0bace1a2-1c90-11e8-9e13-c21a2f8899ed.JPG)

Got above error while uploading  rdl or creating new data source; No info in log as well.

**Comment by jtarquino** [comment]
@sneevand I would recommend to post your question in the https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlreportingservices so the community can help you
