### ISSUE TITLE
Logon.aspx Page disable Register button for other than admin

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services#73]
Hi Guys,

Its not an issues.

We want register button enabled on premises and removed for external users. Is it possible?

Regards,
Navin

**Comment by manceelee** [comment]
I think you need a separate admin portal to add  users, remove register function from login page

**Comment by sneevand** [comment]
Can i have both windows and forms authenticate for custom security  on Logon Page; if X windows users access the url he should be able to view the register button other than that user everyone else will be forms authentication, Is it possible?

**Comment by jtarquino** [comment]
No, the only scenario supported is a single authentication mode

**Comment by manceelee** [comment]
from MS documentation, no you can't do that.  you can put those window login name to the table..
