### ISSUE TITLE
Logon.aspx logo image not displaying

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services#74]
Hi Guys,

We like to show company logo on custom landing page; used below code but the image is not displayed on the page.

      protected System.Web.UI.WebControls.Image ImgLogo;

      private void Page_Load(object sender, System.EventArgs e)
      {
            //Stream fs = FileUpload1.PostedFile.InputStream;
            //BinaryReader br = new BinaryReader(fs);
            //Byte[] bytes = br.ReadBytes((Int32)fs.Length);
            //string base64String = Convert.ToBase64String(bytes, 0, bytes.Length);

            byte[] imageData = null;
            FileInfo fileInfo = new FileInfo("cdrivepath");
            long imageFileLength = fileInfo.Length;
            FileStream fs = new FileStream("cdrivepath", FileMode.Open, FileAccess.Read);
            BinaryReader br = new BinaryReader(fs);
            imageData = br.ReadBytes((int)imageFileLength);
            string base64String = Convert.ToBase64String(imageData, 0, imageData.Length);

            ImgLogo.ImageUrl = "data:image/png;base64," + base64String;

        }

Code works fine on empty page; and other web app projects.

Regards,

Navin

**Comment by jtarquino** [comment]
This project handles the sample code release, bugs and issues
For product issues I would recommend you to contact support and they can help you to identify the best way to solve your problem or use the forums https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlreportingservices
