### ISSUE TITLE
AccessControlAllowCredentials is missing from reporting services properties.

### ISSUE THREAD

**Issue by ganeshmahajan1985** [Microsoft/Reporting-Services#75]
I am using enterprise edition and it dosen't have below properties - 
**AccessControlAllowCredentials
AccessControlAllowHeaders 
AccessControlAllowOrigin 
AccessControlAllowMethods** 

May I know is there anything missing while installation ? or what is the problem exactly ? 
**(Report server version: 13.0.1601.5) 
Report server mode: Native**

Kindly help.
Thanks

**Comment by jtarquino** [comment]
The REST API is available in SSRS 2017 , you seem to be using 2016
