### ISSUE TITLE
SSRS Form authentication ticket question

### ISSUE THREAD

**Issue by manceelee** [Microsoft/Reporting-Services#77]
Hi,

       I have implemented form authentication, everything works fine.  Right now I need to embed a report inside a iframe.  In order to prevent user to see the login page, I have to post login credential to ReportService2010.asmx and get authenticated. 

I have something code like

            ReportServerProxy server = new ReportServerProxy();
            server.Url = "/ReportServer/ReportService2010.asmx";
            server.LogonUser("testuser", "test1234", null);

            Cookie authCookie = server.AuthCookie;
                      if (authCookie != null)
                      {
                          //Internet Set Cookie is a com method which sets the obtained auth token to internet explorer
                          InternetSetCookie(ReportServerURL, null, authCookie.ToString());
                      }

It does return the authCookie, but inside iframe, it still required to type in username & password.  My question is how should i maintain this authenticate cookie(ticket) into browser, so user doesn't need to re-login again.  Thanks for your help!!

**Comment by ganeshmahajan1985** [comment]
Hi @manceelee , I am also looking to implement exact same solution. Hope someone will address this. or kindly update if you got any solution.
Thanks.

**Comment by manceelee** [comment]
Hi @ganeshmahajan1985 
I did few tests 
1.  Modified the logon.aspx page_load to accepted posted user credential, use (httpwebrequest, webclient, httpclient) to post data to report server, it did get authenticated and return response content & cookiecontainer back to web app), but unfortunately the iframe still not authenticated.

2.  Add querystring to iframe report url, it does work, but it's bad practice for security risk
Hope anyone comes out any idea to help us.

**Comment by manceelee** [comment]
couldn't find any solution for it right now

have to encrypt the data and post the data to iframe, modify the page_load on logon.aspx, take this encrypted data and verify the user.
