### ISSUE TITLE
how to prevent cookie injection

### ISSUE THREAD

**Issue by manceelee** [Microsoft/Reporting-Services#82]
Hi all, 

         I have couple iframes to show my reports, when a user got authenticated, he can uses the report url to get into report web portal by existing sqlAuthCookie.   So my consideration is about the cookie injection,  if someone got the admin sqlAuthcookie, will that be a risk.  Any thoughts to prevent this.

Thanks all

**Comment by gboreki** [comment]
Is'nt using https sufficient to prevent someone from stealing the cookie?
