### ISSUE TITLE
Is that possible to add a new aspx page to report server

### ISSUE THREAD

**Issue by manceelee** [Microsoft/Reporting-Services#85]
Hi, 

      I create a new page under the project, but I am not able to access when i deployed to server.  Is there anyway to config this.  

     Also I upload a image under ReportServer Path and display this image on logon.aspx page, but it shows 404 on browse.  

Thanks, 

Ryan

**Comment by Kingslayerz** [comment]
@manceelee  hi, did you got any solution for this? would be great if you share!
