### ISSUE TITLE
Row Level Security 

### ISSUE THREAD

**Issue by manceelee** [Microsoft/Reporting-Services#87]
Hi, 

       Has anyone implemented RLS with forms login, currently we have Power BI on premise, and we don't use Analysis Server to get the data, is there anyway can implement RLS (ex: a user login to the report server, it will only show certain data by passing the parameter - not filtered)  

Thanks,

Ryan

**Comment by gboreki** [comment]
This is currently only possible with live analisys services connections (not embedded data), in that scenario you can use CustomData={{userid}} in the connection string, why can in turn be used to filter the data. For embedded models you need pbidesktop RLS which is still not supported. If you havent posted this yet to ideas.powerbi.com please do so to get more visibility and help prioritize that feature.
