### ISSUE TITLE
GET /Reports incorrectly returns HasParameters and HasDataSources as false

### ISSUE THREAD

**Issue by bladedeyna** [Microsoft/Reporting-Services#91]
The array specific call for /Reports (HTTP GET) appears to return "false" for HasDataSources and HasParameters despite the single equivalent call /Reports({Id}) (HTTP GET) stating that they are "true", which is correct as shown on the server.

**Single Call** Shows true
![getreports_single](https://user-images.githubusercontent.com/24935514/39993506-fd2bc666-576d-11e8-9f5c-21911de449d4.png)

**Array Call** Shows false
![getreports_array](https://user-images.githubusercontent.com/24935514/39993508-fe5e310e-576d-11e8-9cc5-22177ea8b487.png)

**Server shows parameters exist**
![reportparameters](https://user-images.githubusercontent.com/24935514/39993584-3e4f1ca6-576e-11e8-87dd-e1d59735d2c4.png)

**Comment by jtarquino** [comment]
This project handles the sample code release, bugs and issues
For the product issues I would recommend you to contact support and they can help you to identify the best way to get the product fix.
You can also use https://powerbi.microsoft.com/en-us/support/
