### ISSUE TITLE
That assembly does not allow partially trusted callers

### ISSUE THREAD

**Issue by striki70** [Microsoft/Reporting-Services#92]
After configuring the authentication extension as described, I'm getting the following error in the log files:
Microsoft.ReportingServices.Diagnostics.Utilities.UnhandledHttpApplicationException: The report server encountered an unhandled exception in HttpApplication. ---> System.Security.SecurityException: That assembly does not allow partially trusted callers.
   at System.Security.CodeAccessSecurityEngine.ThrowSecurityException(RuntimeAssembly asm, PermissionSet granted, PermissionSet refused, RuntimeMethodHandleInternal rmh, SecurityAction action, Object demand, IPermission permThatFailed)
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.Web.Services.Protocols.SoapReflectedExtension.GetInitializers(Type serviceType, SoapReflectedExtension[] extensions)
   at System.Web.Services.Protocols.SoapClientType..ctor(Type type)
   at System.Web.Services.Protocols.SoapHttpClientProtocol..ctor()
   at ACS.ReportingServices.Security.ReportService2010.ReportingService2010..ctor()
   at ACS.ReportingServices.Security.UILogon.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
   --- End of inner exception stack trace ---;

Any suggestion how to fix this?

**Comment by jtarquino** [comment]
That is an indication your RSSrvPolicy.config isn't modified properly, check the section "o modify the RSSrvPolicy.config file" in [https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample](url)

If you have a default instance of Power BI Report Server you can build , copy the debug folder and run the .\Configure.ps1 script to do all steps all the configuration for you (it has to be a clean default install to run the script)

**Comment by striki70** [comment]
My rssrvpolicy.config file is as follows:

<configuration>
  <mscorlib>
    <security>
      <policy>
        <PolicyLevel version="1">
          <SecurityClasses>
            <SecurityClass Name="AllMembershipCondition" Description="System.Security.Policy.AllMembershipCondition, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="AspNetHostingPermission" Description="System.Web.AspNetHostingPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="DnsPermission" Description="System.Net.DnsPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="EnvironmentPermission" Description="System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="FileIOPermission" Description="System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="FirstMatchCodeGroup" Description="System.Security.Policy.FirstMatchCodeGroup, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="IsolatedStorageFilePermission" Description="System.Security.Permissions.IsolatedStorageFilePermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="NamedPermissionSet" Description="System.Security.NamedPermissionSet"/>
            <SecurityClass Name="PrintingPermission" Description="System.Drawing.Printing.PrintingPermission, System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"/>
            <SecurityClass Name="ReflectionPermission" Description="System.Security.Permissions.ReflectionPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="RegistryPermission" Description="System.Security.Permissions.RegistryPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="SecurityPermission" Description="System.Security.Permissions.SecurityPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="SocketPermission" Description="System.Net.SocketPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="SqlClientPermission" Description="System.Data.SqlClient.SqlClientPermission, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="StrongNameMembershipCondition" Description="System.Security.Policy.StrongNameMembershipCondition, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="UnionCodeGroup" Description="System.Security.Policy.UnionCodeGroup, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="UrlMembershipCondition" Description="System.Security.Policy.UrlMembershipCondition, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="WebPermission" Description="System.Net.WebPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
            <SecurityClass Name="ZoneMembershipCondition" Description="System.Security.Policy.ZoneMembershipCondition, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"/>
          </SecurityClasses>
          <NamedPermissionSets>
            <PermissionSet
                    class="NamedPermissionSet"
                    version="1"
                    Unrestricted="true"
                    Name="FullTrust"
                    Description="Allows full access to all resources"
                        />
            <PermissionSet
                    class="NamedPermissionSet"
                    version="1"
                    Name="Nothing"
                    Description="Denies all resources, including the right to execute"
                        />
            <PermissionSet
                    class="NamedPermissionSet"
                    version="1"
                    Name="Execution">
              <IPermission
                      class="SecurityPermission"
                      version="1"
                      Flags="Execution"
                            />
            </PermissionSet>
          </NamedPermissionSets>
          <CodeGroup
                  class="FirstMatchCodeGroup"
                  version="1"
                  PermissionSetName="Nothing">
            <IMembershipCondition
                    class="AllMembershipCondition"
                    version="1"
                        />
            <CodeGroup
                    class="UnionCodeGroup"
                    version="1"
                    PermissionSetName="Execution"
                    Name="Report_Expressions_Default_Permissions"
                    Description="This code group grants default permissions for code in report expressions and Code element. ">
              <IMembershipCondition
                      class="StrongNameMembershipCondition"
                      version="1"
                      PublicKeyBlob="0024000004800000940000000602000000240000525341310004000001000100512C8E872E28569E733BCB123794DAB55111A0570B3B3D4DE3794153DEA5EFB7C3FEA9F2D8236CFF320C4FD0EAD5F677880BF6C181F296C751C5F6E65B04D3834C02F792FEE0FE452915D44AFE74A0C27E0D8E4B8D04EC52A8E281E01FF47E7D694E6C7275A09AFCBFD8CC82705A06B20FD6EF61EBBA6873E29C8C0F2CAEDDA2"
                            />
            </CodeGroup>
            <CodeGroup
                    class="FirstMatchCodeGroup"
                    version="1"
                    PermissionSetName="Execution"
                    Description="This code group grants MyComputer code Execution permission. ">
              <IMembershipCondition
                        class="ZoneMembershipCondition"
                        version="1"
                        Zone="MyComputer" />
              <CodeGroup
                      class="UnionCodeGroup"
                      version="1"
                      PermissionSetName="FullTrust"
                      Name="Microsoft_Strong_Name"
                      Description="This code group grants code signed with the Microsoft strong name full trust. ">
                <IMembershipCondition
                        class="StrongNameMembershipCondition"
                        version="1"
                        PublicKeyBlob="002400000480000094000000060200000024000052534131000400000100010007D1FA57C4AED9F0A32E84AA0FAEFD0DE9E8FD6AEC8F87FB03766C834C99921EB23BE79AD9D5DCC1DD9AD236132102900B723CF980957FC4E177108FC607774F29E8320E92EA05ECE4E821C0A5EFE8F1645C4C0C93C1AB99285D622CAA652C1DFAD63D745D6F2DE5F17E5EAF0FC4963D261C8A12436518206DC093344D5AD293"
                                />
              </CodeGroup>
              <CodeGroup
                      class="UnionCodeGroup"
                      version="1"
                      PermissionSetName="FullTrust"
                      Name="Ecma_Strong_Name"
                      Description="This code group grants code signed with the ECMA strong name full trust. ">
                <IMembershipCondition
                        class="StrongNameMembershipCondition"
                        version="1"
                        PublicKeyBlob="00000000000000000400000000000000"
                                />
              </CodeGroup>
              <CodeGroup
                      class="UnionCodeGroup"
                      version="1"
                      PermissionSetName="FullTrust"
                      Name="Report_Server_Strong_Name"
                      Description="This code group grants Report Server code full trust. ">
                <IMembershipCondition
                        class="StrongNameMembershipCondition"
                        version="1"
                        PublicKeyBlob="0024000004800000940000000602000000240000525341310004000001000100272736AD6E5F9586BAC2D531EABC3ACC666C2F8EC879FA94F8F7B0327D2FF2ED523448F83C3D5C5DD2DFC7BC99C5286B2C125117BF5CBE242B9D41750732B2BDFFE649C6EFB8E5526D526FDD130095ECDB7BF210809C6CDAD8824FAA9AC0310AC3CBA2AA0523567B2DFA7FE250B30FACBD62D4EC99B94AC47C7D3B28F1F6E4C8"
                                />
              </CodeGroup>
              <CodeGroup
                      class="UnionCodeGroup"
                      version="1"
                      PermissionSetName="FullTrust">
                <IMembershipCondition
                        class="UrlMembershipCondition"
                        version="1"
                        Url="$CodeGen$/*"
                                />
              </CodeGroup>
			  
              <CodeGroup
                class="UnionCodeGroup"
                version="1"
                Name="SecurityExtensionCodeGroup"
                Description="Code group for the sample security extension"
                PermissionSetName="FullTrust">
                <IMembershipCondition 
                  class="UrlMembershipCondition"
                  version="1"
                  Url="C:\Program Files\Microsoft SQL Server\MSRS13.MSSQLSERVER\Reporting Services\ReportServer\bin\ACS.ReportingServices.Security.dll"
                />
              </CodeGroup>

			  <CodeGroup
						class="UnionCodeGroup"
						version="1"
						Name="SecurityExtensionCodeGroup" 
						Description="Code group for the sample security extension"
						PermissionSetName="FullTrust">
				<IMembershipCondition 
						class="UrlMembershipCondition"
						version="1"
						Url="C:\Program Files\Microsoft SQL Server\MSRS13.MSSQLSERVER\Reporting Services\ReportServer\bin\Microsoft.Samples.ReportingServices.CustomSecurity.dll"/>
  			  </CodeGroup>
              <CodeGroup
                      class="UnionCodeGroup"
                      version="1"
                      PermissionSetName="FullTrust"
                      Name="SharePoint_Server_Strong_Name"
                      Description="This code group grants SharePoint Server code full trust. ">
                <IMembershipCondition
                        class="StrongNameMembershipCondition"
                        version="1"
                        PublicKeyBlob="0024000004800000940000000602000000240000525341310004000001000100AFD4A0E7724151D5DD52CB23A30DED7C0091CC01CFE94B2BCD85B3F4EEE3C4D8F6417BFF763763A996D6B2DFC1E7C29BCFB8299779DF8785CDE2C168CEEE480E570725F2468E782A9C2401302CF6DC17E119118ED2011937BAE9698357AD21E8B6DFB40475D16E87EB03C744A5D32899A0DBC596A6B2CFA1E509BE5FBD09FACF"
                                />
              </CodeGroup>
              <CodeGroup
                      class="UnionCodeGroup"
                      version="1"
                      PermissionSetName="FullTrust"
                      Name="Analisys_Server_Strong_Name"
                      Description="This code group grants DataFeedClient.dll full trust. ">
                <IMembershipCondition
                        class="StrongNameMembershipCondition"
                        version="1"
                        PublicKeyBlob="0024000004800000940000000602000000240000525341310004000001000100272736AD6E5F9586BAC2D531EABC3ACC666C2F8EC879FA94F8F7B0327D2FF2ED523448F83C3D5C5DD2DFC7BC99C5286B2C125117BF5CBE242B9D41750732B2BDFFE649C6EFB8E5526D526FDD130095ECDB7BF210809C6CDAD8824FAA9AC0310AC3CBA2AA0523567B2DFA7FE250B30FACBD62D4EC99B94AC47C7D3B28F1F6E4C8"
                                />
              </CodeGroup>
              <CodeGroup
                     class="UnionCodeGroup" 
                     version="1" 
                     PermissionSetName="FullTrust" 
                     Name="OXML_SDK_Strong_Name" 
                     Description="Grants FullTrust to OpenXmlSdk">
                <IMembershipCondition 
                        class="StrongNameMembershipCondition" 
                        version="1" 
                        PublicKeyBlob="0024000004800000940000000602000000240000525341310004000001000100b5fc90e7027f67871e773a8fde8938c81dd402ba65b9201d60593e96c492651e889cc13f1415ebb53fac1131ae0bd333c5ee6021672d9718ea31a8aebd0da0072f25d87dba6fc90ffd598ed4da35e44c398c454307e8e33b8426143daec9f596836f97c8f74750e5975c64e2189f45def46b2a2b1247adc3652bf5c308055da9" 
                                />
              </CodeGroup>
            </CodeGroup>
          </CodeGroup>
        </PolicyLevel>
      </policy>
    </security>
  </mscorlib>
</configuration>

Please note that my security extension is named ACS.ReportingServices.Security.dll
