### ISSUE TITLE
Basic Login Compliance

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services#93]
Hi Guys,

Is it possible to restrict the user to use the password which  is strong and greater than 8 characters?
Is it possible to error out after 3 failed attempts to login and ask him to try after certain amount of time?
Is it possible to  log off user automatically after 30 minutes if idle time?

As GDPR and other security compliance are required above are basic things expected on any external sites...

And directions/code updates would be helpful

Regards,
Navin

**Comment by dnavin** [comment]
And the ability to change password.

**Comment by figuerres** [comment]
@sneevand  and @ghost

this is not a finished product, it's a how to get started ... you need to take from this code how to make a custom security extension, and write one.
not just copy this and use it.

**Comment by sneevand** [comment]
@figuerres thank you for your suggestion, we are unable to achieve it, so raised as issues, appreciate if you can contribute to code rather giving your elderly advise, I respect elders but your advise does not help really.

**Comment by figuerres** [comment]
this is not "elderly advise". 
Really you need to take a good look at what this site is. it's an example of how you can customize reporting services.  no one is writing code here to publish as a finished product.
if you do not know how to write the code you need then you will need to find a developer and pay them to do what you need.

from the sites documentation:
Reporting Services Custom Security Sample
This project will help you to get started with how to deploy a custom security extension to SQL Reporting Services. 

a sample of how to get started. that is all it is.
