### ISSUE TITLE
Culture not found exception

### ISSUE THREAD

**Issue by ayo2kunle** [Microsoft/Reporting-Services#94]
Reports that include embedded images throw an error. All reports are not downloadable as well. Below is the error it generates: 
[CultureNotFoundException: Culture is not supported.
Parameter name: culture
3072 (0x0c00) is an invalid culture identifier.]
   System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride) +12938908
   System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride) +30
   Microsoft.Reporting.WebForms.ReportDataOperation..ctor(IReportServerConnectionProvider connectionProvider, Boolean requiresFullReportLoad) +403
   Microsoft.Reporting.WebForms.HttpHandler.GetHandler(String operationType, IReportServerConnectionProvider connectionProvider) +86
   Microsoft.Reporting.WebForms.HttpHandler.ProcessRequest(HttpContext context) +165
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +188
   System.Web.&lt;&gt;c__DisplayClass285_0.&lt;ExecuteStepImpl&gt;b__0() +26
   System.Web.StepInvoker.Invoke(Action executionStep) +101
   System.Web.&lt;&gt;c__DisplayClass4_0.&lt;Invoke&gt;b__0() +22
   Microsoft.AspNet.TelemetryCorrelation.TelemetryCorrelationHttpModule.OnExecuteRequestStep(HttpContextBase context, Action step) +64
   System.Web.&lt;&gt;c__DisplayClass284_0.&lt;OnExecuteRequestStep&gt;b__0(Action nextStepAction) +54
   System.Web.StepInvoker.Invoke(Action executionStep) +85
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +9980649
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +71

**Comment by jtarquino** [comment]
This project handles the sample code release, bugs and issues
For the product issues I would recommend you to contact support and they can help you to identify the best way to get the product fix.
You can also use https://powerbi.microsoft.com/en-us/support/
