### ISSUE TITLE
How to logout from this application

### ISSUE THREAD

**Issue by MPNIC** [Microsoft/Reporting-Services#95]
The logon functionality works well but how do I implement the logout functionality .

**Comment by jtarquino** [comment]
Currently there is not a easy way to implement it, you can create the idea in https://ideas.powerbi.com/forums/265200-power-bi-ideas 

In other options you can implement an app that uses the LogOff api https://msdn.microsoft.com/en-us/library/reportserviceauthentication.reportserviceauthentication.logoff.aspx , the challenge is how to integrate such app/button in your environment
