### ISSUE TITLE
Logon.aspx embed images

### ISSUE THREAD

**Issue by MPNIC** [Microsoft/Reporting-Services#96]
Hi I would like to embed some images such as logo and header in the logon page , instead on only text which is currently provided . I tried using the normal img src tags but somehow the images are not getting loaded . Can someone help on how they are doing and where they have kept the images folder in Report server directory so that it gets displayed .

**Comment by jtarquino** [comment]
I recommend the forums for help with the implementation https://social.msdn.microsoft.com/Forums/sqlserver/en-US/home?forum=sqlreportingservices

**Comment by Kingslayerz** [comment]
@MPNIC  you got any solution? It would be great if you share!

**Comment by Kingslayerz** [comment]
@jtarquino  have checked the forum but got no luck. can you please help me in this?
