### ISSUE TITLE
new rest api still not using JWT token auth

### ISSUE THREAD

**Issue by figuerres** [Microsoft/Reporting-Services#99]
please make the next release just let me point to my OpenID / Oath 2 server and stop the windows user auth junk from getting in the way.....

**Comment by jtarquino** [comment]
Please submit your idea to https://ideas.powerbi.com/forums/265200-power-bi-ideas?category_id=207604

**Comment by figuerres** [comment]
which begs the  question i have asked before: is SSRS going to be part of Power BI ? is SSRS as a seperate product going to end of life ?

i have tried before to get a clear picture and all i get is crickets ....

**Comment by jtarquino** [comment]
which begs the question i have asked before: is SSRS going to be part of Power BI ?
No
is SSRS as a seperate product going to end of life ?
No

[Power BI Report Server is a superset of Reporting Services ](https://docs.microsoft.com/en-us/power-bi/report-server/get-started )

Any change introduced in Power BI Report Server will be also available in future versions of SSRS

**Comment by figuerres** [comment]
thank you, the last time i tried to get this info there was not a clear answer.

**Comment by figuerres** [comment]
by the way there are over 480 votes over 2 years for OAuth and no action from Microsoft.
so can we wake up someone and have them actually pay attention to what we are begging for ?
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/13195278-oauth

**Comment by jt000** [comment]
@figuerres - SSRS isn't planned to to be moved in it's entirety to powerbi, but there is an effort to make [paginated reports available at some point in the near future](https://whitepages.unlimitedviz.com/2018/03/road-ahead-sql-server-reporting-services-power-bi-report-server/).

**Comment by figuerres** [comment]
@jt000 my concerns and pain points have to do with costs and with modern app integration.

in my current project / role   we have been using SSRS to do our reports, the users of the reports will be our staff and contractors and customers.
with the current SSRS 2016 / 2017   we can do paginated reports and we know the license costs to do that. 

our app is angular 4/5/6  typescript based and our login system is using Identity Server  to issue JWT tokens to users.
we are not using Windows AD  at all in this web app.   that way we can have customers who can login and use our app. no AD accounts needed.
i mention this in part due to seeing a Microsoft article that talks about uisng OAuth but really it was ADFS which does not help my case.

Power BI  seems to have  higher costs than using SSRS. 
but the talk i see is that Microsoft is pushing Power BI and  SSRS still depends on AD / Windows User Accounts.

if SSRS would be updated to just let me tell it where my STS server is  and map some roles between them that would vastly improve things for our app.

what we currently wind up doing is creating a set of machine local accounts that we use like a role 
and then taking our users role from our STS and mapping that do one of the local accounts created on the report server machine to manage what reports can be run.

I am glad to see the new rest API package in SSRS 2017 that is a great move in what i think is a good direction.
now make Oauth / Open ID Connect an option and we get a whole lot closer to cleanly integrating this.

right now SSRS has a "custom Auth" and i am looking at the new version to see if i can turn that into OpenID , the prior versions had a lot of  issues and it looks like the 2017 version might be better.
if i can make it work that will be great.

i just want to pass a token and have SSRS use it.
